// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

import 'dart:typed_data' show Uint8List;
import 'flat_buffers.dart' as fb;

class FlatDb {
  FlatDb._(this._bc, this._bcOffset);
  factory FlatDb(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<FlatDb> reader = _FlatDbReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  bool get isTableCreated => const fb.BoolReader().vTableGet(_bc, _bcOffset, 4, false);
  int get themeMode => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 6, 0);
  double get fontSize => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 8, 0.0);
  String? get appColor => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  int get holdingPeriod => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 12, 0);
  int get interestType => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 14, 0);
  int get compoundingFrequency => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 16, 0);
  int get scheduledBackUpTimeHour => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 18, 0);
  int get scheduledBackUpTimeMinute => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 20, 0);
  String? get driveIdToken => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 22);
  String? get driveAccessToken => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 24);
  String? get driveFolderId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 26);
  String? get driveFileId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 28);
  int get driveUser => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 30, 0);

    @override
  String toString() {
    return 'FlatDb{isTableCreated: $isTableCreated, themeMode: $themeMode, fontSize: $fontSize, appColor: $appColor, holdingPeriod: $holdingPeriod, interestType: $interestType, compoundingFrequency: $compoundingFrequency, scheduledBackUpTimeHour: $scheduledBackUpTimeHour, scheduledBackUpTimeMinute: $scheduledBackUpTimeMinute, driveIdToken: $driveIdToken, driveAccessToken: $driveAccessToken, driveFolderId: $driveFolderId, driveFileId: $driveFileId, driveUser: $driveUser}';
  }
}


class _FlatDbReader extends fb.TableReader<FlatDb> {
  const _FlatDbReader();

  @override
  FlatDb createObject(fb.BufferContext bc, int offset) => FlatDb._(bc, offset);
}

class FlatDbObjectBuilder extends fb.ObjectBuilder {
  bool? isTableCreated;
  int? themeMode;
  double? fontSize;
  String? appColor;
  int? holdingPeriod;
  int? interestType;
  int? compoundingFrequency;
  int? scheduledBackUpTimeHour;
  int? scheduledBackUpTimeMinute;
  String? driveIdToken;
  String? driveAccessToken;
  String? driveFolderId;
  String? driveFileId;
  int? driveUser;

  FlatDbObjectBuilder(
      {this.isTableCreated,
      this.themeMode,
      this.fontSize,
      this.appColor,
      this.holdingPeriod,
      this.interestType,
      this.compoundingFrequency,
      this.scheduledBackUpTimeHour,
      this.scheduledBackUpTimeMinute,
      this.driveIdToken,
      this.driveAccessToken,
      this.driveFolderId,
      this.driveFileId,
      this.driveUser,
      });

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? appColorOffset =
        appColor == null ? null : fbBuilder.writeString(appColor!);
    final int? driveAccessTokenOffset = driveAccessToken == null ? null
        : fbBuilder.writeString(driveAccessToken!);
    final int? driveIdTokenOffset = driveIdToken == null ? null
        : fbBuilder.writeString(driveIdToken!);
    final int? driveFolderIdOffset = driveFolderId == null ? null
        : fbBuilder.writeString(driveFolderId!);  
    final int? driveFileIdOffset = driveFileId == null ? null
        : fbBuilder.writeString(driveFileId!);
    fbBuilder.startTable(14);
    fbBuilder.addBool(0, isTableCreated);
    fbBuilder.addInt8(1, themeMode);
    fbBuilder.addFloat32(2, fontSize);
    fbBuilder.addOffset(3, appColorOffset);
    fbBuilder.addInt8(4, holdingPeriod);
    fbBuilder.addInt8(5, interestType);
    fbBuilder.addInt8(6, compoundingFrequency);
    fbBuilder.addInt8(7, scheduledBackUpTimeHour);
    fbBuilder.addInt8(8, scheduledBackUpTimeMinute);
    fbBuilder.addOffset(9, driveIdTokenOffset);
    fbBuilder.addOffset(10, driveAccessTokenOffset);
    fbBuilder.addOffset(11, driveFolderIdOffset);
    fbBuilder.addOffset(12, driveFileIdOffset);
    fbBuilder.addInt8(13, driveUser);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
