// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

import 'dart:typed_data' show Uint8List;
import 'flat_buffers.dart' as fb;

class FlatDb {
  FlatDb._(this._bc, this._bcOffset);
  factory FlatDb(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<FlatDb> reader = _FlatDbReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  bool get isTableCreated =>
      const fb.BoolReader().vTableGet(_bc, _bcOffset, 4, false);
  int get themeMode => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 6, 0);
  String? get appColor =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get holdingPeriod =>
      const fb.Int8Reader().vTableGet(_bc, _bcOffset, 10, 0);
  double get interestRate =>
      const fb.Float32Reader().vTableGet(_bc, _bcOffset, 12, 0.0);
  int get interestType =>
      const fb.Int8Reader().vTableGet(_bc, _bcOffset, 14, 0);
  int get interestFrequency =>
      const fb.Int8Reader().vTableGet(_bc, _bcOffset, 16, 0);
  int get scheduledBackUpTimeHour =>
      const fb.Int8Reader().vTableGet(_bc, _bcOffset, 18, 0);
  int get scheduledBackUpTimeMinute =>
      const fb.Int8Reader().vTableGet(_bc, _bcOffset, 20, 0);
  String? get driveAccessToken =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 22);
  int get driveAccessTokenExpires =>
      const fb.Int64Reader().vTableGet(_bc, _bcOffset, 24, 0);
  String? get driveFileId =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 26);
  int get driveUser => const fb.Int8Reader().vTableGet(_bc, _bcOffset, 28, 0);
  bool get isBackUpRegistered =>
      const fb.BoolReader().vTableGet(_bc, _bcOffset, 30, false);
  int get dbUpdateTime =>
      const fb.Int64Reader().vTableGet(_bc, _bcOffset, 32, 0);
  String? get backupTaskId =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 34);
  bool get secure => const fb.BoolReader().vTableGet(_bc, _bcOffset, 36, false);
  String? get displayName =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 38);
  String? get email =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 40);
  String? get photourl =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 42);
  List<int>? get photo =>
      const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 44);

  @override
  String toString() {
    return 'FlatDb{isTableCreated: $isTableCreated, themeMode: $themeMode, appColor: $appColor, holdingPeriod: $holdingPeriod, interestRate: $interestRate, interestType: $interestType, interestFrequency: $interestFrequency, scheduledBackUpTimeHour: $scheduledBackUpTimeHour, scheduledBackUpTimeMinute: $scheduledBackUpTimeMinute, driveAccessToken: $driveAccessToken, driveAccessTokenExpires: $driveAccessTokenExpires, driveFileId: $driveFileId, driveUser: $driveUser, isBackUpRegistered: $isBackUpRegistered, dbUpdateTime: $dbUpdateTime, backupTaskId: $backupTaskId, secure: $secure, displayName: $displayName, email: $email, photourl: $photourl, photo: $photo}';
  }
}

class _FlatDbReader extends fb.TableReader<FlatDb> {
  const _FlatDbReader();

  @override
  FlatDb createObject(fb.BufferContext bc, int offset) => FlatDb._(bc, offset);
}

class FlatDbObjectBuilder extends fb.ObjectBuilder {
  bool? isTableCreated;
  int? themeMode;
  String? appColor;
  int? holdingPeriod;
  double? interestRate;
  int? interestType;
  int? interestFrequency;
  int? scheduledBackUpTimeHour;
  int? scheduledBackUpTimeMinute;
  String? driveAccessToken;
  int? driveAccessTokenExpires;
  String? driveFileId;
  int? driveUser;
  bool? isBackUpRegistered;
  int? dbUpdateTime;
  String? backupTaskId;
  bool? secure;
  String? displayName;
  String? email;
  String? photourl;
  List<int>? photo;

  FlatDbObjectBuilder({
    this.isTableCreated,
    this.themeMode,
    this.appColor,
    this.holdingPeriod,
    this.interestRate,
    this.interestType,
    this.interestFrequency,
    this.scheduledBackUpTimeHour,
    this.scheduledBackUpTimeMinute,
    this.driveAccessToken,
    this.driveAccessTokenExpires,
    this.driveFileId,
    this.driveUser,
    this.isBackUpRegistered,
    this.dbUpdateTime,
    this.displayName,
    this.email,
    this.photourl,
    this.backupTaskId,
    this.secure,
    this.photo,
  });

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? appColorOffset = appColor == null
        ? null
        : fbBuilder.writeString(appColor!);
    final int? driveAccessTokenOffset = driveAccessToken == null
        ? null
        : fbBuilder.writeString(driveAccessToken!);
    final int? driveFileIdOffset = driveFileId == null
        ? null
        : fbBuilder.writeString(driveFileId!);
    final int? displayNameOffset = displayName == null
        ? null
        : fbBuilder.writeString(displayName!);
    final int? emailOffset = email == null
        ? null
        : fbBuilder.writeString(email!);
    final int? photourlOffset = photourl == null
        ? null
        : fbBuilder.writeString(photourl!);
    final int? backupTaskIdOffset = backupTaskId == null
        ? null
        : fbBuilder.writeString(backupTaskId!);
    final int? photoOffset = photo == null
        ? null
        : fbBuilder.writeListUint8(photo!);
    fbBuilder.startTable(21);
    fbBuilder.addBool(0, isTableCreated);
    fbBuilder.addInt8(1, themeMode);
    fbBuilder.addOffset(2, appColorOffset);
    fbBuilder.addInt8(3, holdingPeriod);
    fbBuilder.addFloat32(4, interestRate);
    fbBuilder.addInt8(5, interestType);
    fbBuilder.addInt8(6, interestFrequency);
    fbBuilder.addInt8(7, scheduledBackUpTimeHour);
    fbBuilder.addInt8(8, scheduledBackUpTimeMinute);
    fbBuilder.addOffset(9, driveAccessTokenOffset);
    fbBuilder.addInt64(10, driveAccessTokenExpires);
    fbBuilder.addOffset(11, driveFileIdOffset);
    fbBuilder.addInt8(12, driveUser);
    fbBuilder.addBool(13, isBackUpRegistered);
    fbBuilder.addInt64(14, dbUpdateTime);
    fbBuilder.addOffset(15, backupTaskIdOffset);
    fbBuilder.addBool(16, secure);
    fbBuilder.addOffset(17, displayNameOffset);
    fbBuilder.addOffset(18, emailOffset);
    fbBuilder.addOffset(19, photourlOffset);
    fbBuilder.addOffset(20, photoOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
