targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run `pub run build_runner doctor` to check your config.
      source_gen:combining_builder:
        generate_for:
          # Example glob for only the Dart files under `lib/models`
          - lib/provider/*.dart
#       objectbox_generator|resolver:
#         enabled: true
#         generate_for: 
#           - lib/objectbox/*.dart
#       objectbox_generator|generator:
#         enabled: true      
#       # objectbox_generator:generator:
#         generate_for: 
#           - lib/objectbox/*.dart

# builders:
#   # Finds all classes annotated with @Entity annotation and creates intermediate files for the generator.
#   # It's executed multiple times, once per file
#   resolver:
#     import: "package:objectbox_generator/objectbox_generator.dart"
#     builder_factories: ["entityResolverFactory"]
#     # build_extensions: Required. A map from input extension to the list of output extensions that may be created
#     # for that input. This must match the merged buildExtensions maps from each Builder in builder_factories.
#     build_extensions: {'.dart': ['.objectbox.info']}
#     auto_apply: dependents
#     build_to: cache

#   # Writes objectbox_model.dart and objectbox-model.json from the prepared .objectbox.info files found in the repo.
#   generator:
#     import: "package:objectbox_generator/objectbox_generator.dart"
#     builder_factories: ["codeGeneratorFactory"]
#     # build_extensions: Required. A map from input extension to the list of output extensions that may be created
#     # for that input. This must match the merged buildExtensions maps from each Builder in builder_factories.
#     build_extensions:
#       "$lib$": ["objectbox.g.dart"]
#       "$test": ["objectbox.g.dart"]
#     required_inputs: ['.objectbox.info']
#     auto_apply: dependents
#     build_to: source