table FlatDB {
  is_table_created: bool;
  theme_mode: int8;
  app_color: string;
  holding_period:int8;
  interest_rate:float;
  interest_type:int8;
  interest_frequency:int8;
  scheduled_back_up_time_hour: int8;
  scheduled_back_up_time_minute: int8;
  drive_access_token: string;
  drive_access_token_expires: int64;
  drive_file_id: string;
  drive_user: int8;
  is_back_up_registered: bool;
  db_update_time: int64;
  backup_task_id: string;
  secure: bool;
  display_name: string;
  email: string;
  photourl: string;
  photo:[ubyte];
  default_lock_in_days:int8;
  default_early_redemption_charge:double;
}
