name: loanx
description: "A loanx calculator app that helps you calculate your monthly loanx payments. It also helps you understand the different types of loanxs and how much you can borrow. loanx is available on both Android and iOS platforms, making it accessible to a wide range of users."
publish_to: "none"
version: 1.0.1+4

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  intl: ^0.20.3
  intl_phone_number_input:
    git: https://github.com/kumsumit/intl_phone_number_input.git
  sqflite_sqlcipher:
    git: https://github.com/kumsumit/sqflite_sqlcipher.git
  flutter_secure_storage:
    git: https://github.com/kumsumit/flutter_secure_storage.git 
  auto_size_text:
    git: https://github.com/sumitsharansatsangi/auto_size_text.git
  encrypt: ^5.0.3
  archive: ^4.0.9
  # faker: ^2.2.0
  path: ^1.9.1
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  flutter_native_splash: 
    git: https://github.com/sumitsharansatsangi/flutter_native_splash.git
  url_launcher:
    git: https://github.com/kumsumit/url_launcher.git
  # flutter_screenutil:
  #   git: https://github.com/sumitsharansatsangi/flutter_screenutil.git
  flutter_typeahead: 
    git: https://github.com/sumitsharansatsangi/flutter_typeahead.git
  # firebase_auth: ^5.3.3
  # firebase_core: ^3.8.0
  # flutter_exif_rotation: ^0.5.2
  google_sign_in:
    git: https://github.com/kumsumit/google_sign_in.git
  googleapis: ^16.0.0
  # googleapis_auth: ^1.6.0
  http: ^1.6.0
  hooks_riverpod: 
    git: https://github.com/kumsumit/hooks_riverpod.git
  flutter_hooks:
    git: https://github.com/kumsumit/flutter_hooks.git
  printing:
    git: https://github.com/kumsumit/printing.git
  pdf:
    git: https://github.com/kumsumit/pdf.git  
  # fluttertoast:
  #   git: https://github.com/sumitsharansatsangi/fluttertoast.git
  fuzzywuzzy: ^1.2.0
  riverpod_annotation: 
    git: https://github.com/kumsumit/riverpod_annotation.git
  # extension_google_sign_in_as_googleapis_auth: ^2.0.12
  # flex_color_picker: ^3.6.0
  flutter_color_picker_plus:
    git: https://github.com/sumitsharansatsangi/flutter_color_picker_plus.git
  image_picker:
    git: https://github.com/kumsumit/image_picker.git
  local_auth:
    git: https://github.com/kumsumit/local_auth.git  
  workmanager:
    git: https://github.com/kumsumit/workmanager.git
  internet_connection_checker_plus:
    git: https://github.com/sumitsharansatsangi/internet_connection_checker_plus.git
  share_plus:
    git: https://github.com/kumsumit/share_plus.git
  in_app_update:
    git: https://github.com/sumitsharansatsangi/flutter_in_app_update.git
  grouped_list: ^6.0.0 
  shorebird_code_push: ^2.0.7 
  # device_preview:
  #   git: https://github.com/sumitsharansatsangi/device_preview.git

  # background_fetch:
  #   git: https://github.com/sumitsharansatsangi/flutter_background_fetch.git  

dev_dependencies:
  # integration_test:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.3
  riverpod_generator:
    git: https://github.com/kumsumit/riverpod_generator.git
  riverpod_lint:
    git: https://github.com/kumsumit/riverpod_lint.git
  icons_launcher:
    git: "https://github.com/kumsumit/icons_launcher.git"    
  

dependency_overrides: 
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - shorebird.yaml
  fonts:
    - family: K
      fonts:
        - asset: assets/fonts/K.ttf

flutter_native_splash: 
  color: '#9fd09f'
  color_dark: '#000f0f'
  android: true
  ios: true
  image_android: 'logo_light.png'
  image_dark_android: 'logo_dark.png'
  image_ios: 'logo_light.png'
  image_dark_ios: 'logo_dark.png'
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: '#9fd09f'
    color_dark: '#000f0f'
    image: 'android_12_light.png'
    image_dark: 'android_12_dark.png'

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
             
#  logo_color: #161f2cff            