// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1670688211;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__network__account_bootstrap_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "account_bootstrap",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::account_bootstrap(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__block_public_lender_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "block_public_lender",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_profile_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::block_public_lender(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_profile_id,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__connect_and_hello_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "connect_and_hello",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_client_build = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::connect_and_hello(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_client_build,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__create_pending_loan_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_pending_loan",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_workspace_id = <String>::sse_decode(&mut deserializer);
            let api_operation_id = <String>::sse_decode(&mut deserializer);
            let api_borrower_phone_e164 = <String>::sse_decode(&mut deserializer);
            let api_borrower_name = <String>::sse_decode(&mut deserializer);
            let api_loan_payload_json = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::create_pending_loan(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_workspace_id,
                                api_operation_id,
                                api_borrower_phone_e164,
                                api_borrower_name,
                                api_loan_payload_json,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::simple::greet(api_name))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::simple::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__network__list_shared_loans_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_shared_loans",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_limit = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::list_shared_loans(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_limit,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__logout_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "logout_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::logout_session(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__my_lender_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "my_lender_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::my_lender_profile(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__publish_public_lender_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "publish_public_lender",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_display_name = <String>::sse_decode(&mut deserializer);
            let api_locality = <String>::sse_decode(&mut deserializer);
            let api_city = <String>::sse_decode(&mut deserializer);
            let api_postal_code = <String>::sse_decode(&mut deserializer);
            let api_country_code = <String>::sse_decode(&mut deserializer);
            let api_minimum_loan_minor = <String>::sse_decode(&mut deserializer);
            let api_maximum_loan_minor = <String>::sse_decode(&mut deserializer);
            let api_currency = <String>::sse_decode(&mut deserializer);
            let api_currency_scale = <u32>::sse_decode(&mut deserializer);
            let api_categories = <Vec<String>>::sse_decode(&mut deserializer);
            let api_available = <bool>::sse_decode(&mut deserializer);
            let api_published = <bool>::sse_decode(&mut deserializer);
            let api_public_description = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::publish_public_lender(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_display_name,
                                api_locality,
                                api_city,
                                api_postal_code,
                                api_country_code,
                                api_minimum_loan_minor,
                                api_maximum_loan_minor,
                                api_currency,
                                api_currency_scale,
                                api_categories,
                                api_available,
                                api_published,
                                api_public_description,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__push_financial_event_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "push_financial_event",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_workspace_id = <String>::sse_decode(&mut deserializer);
            let api_operation_id = <String>::sse_decode(&mut deserializer);
            let api_loan_id = <String>::sse_decode(&mut deserializer);
            let api_event_type = <String>::sse_decode(&mut deserializer);
            let api_amount_minor = <String>::sse_decode(&mut deserializer);
            let api_currency = <String>::sse_decode(&mut deserializer);
            let api_currency_scale = <u32>::sse_decode(&mut deserializer);
            let api_effective_date = <String>::sse_decode(&mut deserializer);
            let api_payment_method = <Option<String>>::sse_decode(&mut deserializer);
            let api_reference_number = <Option<String>>::sse_decode(&mut deserializer);
            let api_reverses_event_id = <Option<String>>::sse_decode(&mut deserializer);
            let api_reason = <Option<String>>::sse_decode(&mut deserializer);
            let api_principal_minor = <Option<String>>::sse_decode(&mut deserializer);
            let api_loan_date = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::push_financial_event(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_workspace_id,
                                api_operation_id,
                                api_loan_id,
                                api_event_type,
                                api_amount_minor,
                                api_currency,
                                api_currency_scale,
                                api_effective_date,
                                api_payment_method,
                                api_reference_number,
                                api_reverses_event_id,
                                api_reason,
                                api_principal_minor,
                                api_loan_date,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__push_mutation_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "push_mutation",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_workspace_id = <String>::sse_decode(&mut deserializer);
            let api_operation_id = <String>::sse_decode(&mut deserializer);
            let api_entity_type = <String>::sse_decode(&mut deserializer);
            let api_entity_id = <String>::sse_decode(&mut deserializer);
            let api_operation = <String>::sse_decode(&mut deserializer);
            let api_expected_revision = <i64>::sse_decode(&mut deserializer);
            let api_payload_json = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::push_mutation(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_workspace_id,
                                api_operation_id,
                                api_entity_type,
                                api_entity_id,
                                api_operation,
                                api_expected_revision,
                                api_payload_json,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__refresh_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "refresh_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_refresh_token = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::refresh_session(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_refresh_token,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__report_public_lender_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "report_public_lender",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_profile_id = <String>::sse_decode(&mut deserializer);
            let api_reason = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::report_public_lender(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_profile_id,
                                api_reason,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__request_chat_credentials_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "request_chat_credentials",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::request_chat_credentials(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__request_otp_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "request_otp",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_phone_e164 = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::request_otp(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_phone_e164,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__search_public_lenders_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "search_public_lenders",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_area = <u32>::sse_decode(&mut deserializer);
            let api_query = <String>::sse_decode(&mut deserializer);
            let api_limit = <u32>::sse_decode(&mut deserializer);
            let api_after_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::search_public_lenders(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_area,
                                api_query,
                                api_limit,
                                api_after_id,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__update_language_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_language",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_preferred_language = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::update_language(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_access_token,
                                api_preferred_language,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__network__verify_otp_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verify_otp",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_server_address = <String>::sse_decode(&mut deserializer);
            let api_server_name = <String>::sse_decode(&mut deserializer);
            let api_trusted_certificate_pem = <String>::sse_decode(&mut deserializer);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_challenge_id = <String>::sse_decode(&mut deserializer);
            let api_phone_e164 = <String>::sse_decode(&mut deserializer);
            let api_otp = <String>::sse_decode(&mut deserializer);
            let api_preferred_language = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::network::verify_otp(
                                api_server_address,
                                api_server_name,
                                api_trusted_certificate_pem,
                                api_device_id,
                                api_challenge_id,
                                api_phone_e164,
                                api_otp,
                                api_preferred_language,
                            )
                            .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::network::AccountBootstrap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_userId = <String>::sse_decode(deserializer);
        let mut var_workspaceId = <String>::sse_decode(deserializer);
        let mut var_selfPartyId = <String>::sse_decode(deserializer);
        let mut var_phoneE164 = <String>::sse_decode(deserializer);
        let mut var_preferredLanguage = <String>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::AccountBootstrap {
            success: var_success,
            user_id: var_userId,
            workspace_id: var_workspaceId,
            self_party_id: var_selfPartyId,
            phone_e164: var_phoneE164,
            preferred_language: var_preferredLanguage,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::network::AuthTokens {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_transportUnavailable = <bool>::sse_decode(deserializer);
        let mut var_accessToken = <String>::sse_decode(deserializer);
        let mut var_refreshToken = <String>::sse_decode(deserializer);
        let mut var_userId = <String>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::AuthTokens {
            success: var_success,
            transport_unavailable: var_transportUnavailable,
            access_token: var_accessToken,
            refresh_token: var_refreshToken,
            user_id: var_userId,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::network::ChatCredentials {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_jid = <String>::sse_decode(deserializer);
        let mut var_accessToken = <String>::sse_decode(deserializer);
        let mut var_expiresAtMs = <i64>::sse_decode(deserializer);
        let mut var_websocketUrl = <String>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::ChatCredentials {
            success: var_success,
            jid: var_jid,
            access_token: var_accessToken,
            expires_at_ms: var_expiresAtMs,
            websocket_url: var_websocketUrl,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::network::LenderSearchResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_lenders = <Vec<crate::api::network::PublicLender>>::sse_decode(deserializer);
        let mut var_nextAfterId = <String>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::LenderSearchResult {
            success: var_success,
            lenders: var_lenders,
            next_after_id: var_nextAfterId,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::network::PublicLender> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::network::PublicLender>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::network::SharedLoanSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::network::SharedLoanSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::network::SharedRepayment> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::network::SharedRepayment>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::network::MyLenderProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_profile = <Option<crate::api::network::PublicLender>>::sse_decode(deserializer);
        let mut var_published = <bool>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::MyLenderProfile {
            success: var_success,
            profile: var_profile,
            published: var_published,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::network::NetworkResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::NetworkResult {
            success: var_success,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::network::PublicLender> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::network::PublicLender>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::network::OtpChallenge {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_challengeId = <String>::sse_decode(deserializer);
        let mut var_expiresInSeconds = <u32>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::OtpChallenge {
            success: var_success,
            challenge_id: var_challengeId,
            expires_in_seconds: var_expiresInSeconds,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::network::PendingLoanInvitation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_invitationId = <String>::sse_decode(deserializer);
        let mut var_linkedToExistingAccount = <bool>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::PendingLoanInvitation {
            success: var_success,
            invitation_id: var_invitationId,
            linked_to_existing_account: var_linkedToExistingAccount,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::network::PublicLender {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_locality = <String>::sse_decode(deserializer);
        let mut var_city = <String>::sse_decode(deserializer);
        let mut var_postalCode = <String>::sse_decode(deserializer);
        let mut var_countryCode = <String>::sse_decode(deserializer);
        let mut var_minimumLoanMinor = <i64>::sse_decode(deserializer);
        let mut var_maximumLoanMinor = <i64>::sse_decode(deserializer);
        let mut var_currency = <String>::sse_decode(deserializer);
        let mut var_currencyScale = <u32>::sse_decode(deserializer);
        let mut var_categories = <Vec<String>>::sse_decode(deserializer);
        let mut var_verificationLevel = <String>::sse_decode(deserializer);
        let mut var_available = <bool>::sse_decode(deserializer);
        let mut var_publicDescription = <String>::sse_decode(deserializer);
        return crate::api::network::PublicLender {
            id: var_id,
            display_name: var_displayName,
            locality: var_locality,
            city: var_city,
            postal_code: var_postalCode,
            country_code: var_countryCode,
            minimum_loan_minor: var_minimumLoanMinor,
            maximum_loan_minor: var_maximumLoanMinor,
            currency: var_currency,
            currency_scale: var_currencyScale,
            categories: var_categories,
            verification_level: var_verificationLevel,
            available: var_available,
            public_description: var_publicDescription,
        };
    }
}

impl SseDecode for crate::api::network::ServerHello {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_protocolMajor = <u32>::sse_decode(deserializer);
        let mut var_serverBuild = <String>::sse_decode(deserializer);
        let mut var_maximumFrameBytes = <u32>::sse_decode(deserializer);
        let mut var_capabilities = <Vec<String>>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::ServerHello {
            success: var_success,
            protocol_major: var_protocolMajor,
            server_build: var_serverBuild,
            maximum_frame_bytes: var_maximumFrameBytes,
            capabilities: var_capabilities,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::network::SharedLoanListResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_loans = <Vec<crate::api::network::SharedLoanSummary>>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        return crate::api::network::SharedLoanListResult {
            success: var_success,
            loans: var_loans,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::api::network::SharedLoanSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_loanId = <String>::sse_decode(deserializer);
        let mut var_lenderPartyId = <String>::sse_decode(deserializer);
        let mut var_borrowerPartyId = <String>::sse_decode(deserializer);
        let mut var_principalMinor = <i64>::sse_decode(deserializer);
        let mut var_currency = <String>::sse_decode(deserializer);
        let mut var_currencyScale = <u32>::sse_decode(deserializer);
        let mut var_lifecycle = <String>::sse_decode(deserializer);
        let mut var_loanDate = <String>::sse_decode(deserializer);
        let mut var_maturityDate = <String>::sse_decode(deserializer);
        let mut var_repayments =
            <Vec<crate::api::network::SharedRepayment>>::sse_decode(deserializer);
        return crate::api::network::SharedLoanSummary {
            loan_id: var_loanId,
            lender_party_id: var_lenderPartyId,
            borrower_party_id: var_borrowerPartyId,
            principal_minor: var_principalMinor,
            currency: var_currency,
            currency_scale: var_currencyScale,
            lifecycle: var_lifecycle,
            loan_date: var_loanDate,
            maturity_date: var_maturityDate,
            repayments: var_repayments,
        };
    }
}

impl SseDecode for crate::api::network::SharedRepayment {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_eventType = <String>::sse_decode(deserializer);
        let mut var_amountMinor = <i64>::sse_decode(deserializer);
        let mut var_currency = <String>::sse_decode(deserializer);
        let mut var_currencyScale = <u32>::sse_decode(deserializer);
        let mut var_paymentDate = <String>::sse_decode(deserializer);
        let mut var_recordedAt = <String>::sse_decode(deserializer);
        let mut var_paymentMethod = <String>::sse_decode(deserializer);
        let mut var_reversesEventId = <String>::sse_decode(deserializer);
        return crate::api::network::SharedRepayment {
            id: var_id,
            event_type: var_eventType,
            amount_minor: var_amountMinor,
            currency: var_currency,
            currency_scale: var_currencyScale,
            payment_date: var_paymentDate,
            recorded_at: var_recordedAt,
            payment_method: var_paymentMethod,
            reverses_event_id: var_reversesEventId,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__network__account_bootstrap_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__network__block_public_lender_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__network__connect_and_hello_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__network__create_pending_loan_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__network__list_shared_loans_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__network__logout_session_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__network__my_lender_profile_impl(port, ptr, rust_vec_len, data_len),
        10 => {
            wire__crate__api__network__publish_public_lender_impl(port, ptr, rust_vec_len, data_len)
        }
        11 => {
            wire__crate__api__network__push_financial_event_impl(port, ptr, rust_vec_len, data_len)
        }
        12 => wire__crate__api__network__push_mutation_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__network__refresh_session_impl(port, ptr, rust_vec_len, data_len),
        14 => {
            wire__crate__api__network__report_public_lender_impl(port, ptr, rust_vec_len, data_len)
        }
        15 => wire__crate__api__network__request_chat_credentials_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        16 => wire__crate__api__network__request_otp_impl(port, ptr, rust_vec_len, data_len),
        17 => {
            wire__crate__api__network__search_public_lenders_impl(port, ptr, rust_vec_len, data_len)
        }
        18 => wire__crate__api__network__update_language_impl(port, ptr, rust_vec_len, data_len),
        19 => wire__crate__api__network__verify_otp_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        5 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::AccountBootstrap {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.user_id.into_into_dart().into_dart(),
            self.workspace_id.into_into_dart().into_dart(),
            self.self_party_id.into_into_dart().into_dart(),
            self.phone_e164.into_into_dart().into_dart(),
            self.preferred_language.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::AccountBootstrap
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::AccountBootstrap>
    for crate::api::network::AccountBootstrap
{
    fn into_into_dart(self) -> crate::api::network::AccountBootstrap {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::AuthTokens {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.transport_unavailable.into_into_dart().into_dart(),
            self.access_token.into_into_dart().into_dart(),
            self.refresh_token.into_into_dart().into_dart(),
            self.user_id.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::AuthTokens
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::AuthTokens>
    for crate::api::network::AuthTokens
{
    fn into_into_dart(self) -> crate::api::network::AuthTokens {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::ChatCredentials {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.jid.into_into_dart().into_dart(),
            self.access_token.into_into_dart().into_dart(),
            self.expires_at_ms.into_into_dart().into_dart(),
            self.websocket_url.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::ChatCredentials
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::ChatCredentials>
    for crate::api::network::ChatCredentials
{
    fn into_into_dart(self) -> crate::api::network::ChatCredentials {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::LenderSearchResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.lenders.into_into_dart().into_dart(),
            self.next_after_id.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::LenderSearchResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::LenderSearchResult>
    for crate::api::network::LenderSearchResult
{
    fn into_into_dart(self) -> crate::api::network::LenderSearchResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::MyLenderProfile {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.profile.into_into_dart().into_dart(),
            self.published.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::MyLenderProfile
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::MyLenderProfile>
    for crate::api::network::MyLenderProfile
{
    fn into_into_dart(self) -> crate::api::network::MyLenderProfile {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::NetworkResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::NetworkResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::NetworkResult>
    for crate::api::network::NetworkResult
{
    fn into_into_dart(self) -> crate::api::network::NetworkResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::OtpChallenge {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.challenge_id.into_into_dart().into_dart(),
            self.expires_in_seconds.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::OtpChallenge
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::OtpChallenge>
    for crate::api::network::OtpChallenge
{
    fn into_into_dart(self) -> crate::api::network::OtpChallenge {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::PendingLoanInvitation {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.invitation_id.into_into_dart().into_dart(),
            self.linked_to_existing_account.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::PendingLoanInvitation
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::PendingLoanInvitation>
    for crate::api::network::PendingLoanInvitation
{
    fn into_into_dart(self) -> crate::api::network::PendingLoanInvitation {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::PublicLender {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.locality.into_into_dart().into_dart(),
            self.city.into_into_dart().into_dart(),
            self.postal_code.into_into_dart().into_dart(),
            self.country_code.into_into_dart().into_dart(),
            self.minimum_loan_minor.into_into_dart().into_dart(),
            self.maximum_loan_minor.into_into_dart().into_dart(),
            self.currency.into_into_dart().into_dart(),
            self.currency_scale.into_into_dart().into_dart(),
            self.categories.into_into_dart().into_dart(),
            self.verification_level.into_into_dart().into_dart(),
            self.available.into_into_dart().into_dart(),
            self.public_description.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::PublicLender
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::PublicLender>
    for crate::api::network::PublicLender
{
    fn into_into_dart(self) -> crate::api::network::PublicLender {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::ServerHello {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.protocol_major.into_into_dart().into_dart(),
            self.server_build.into_into_dart().into_dart(),
            self.maximum_frame_bytes.into_into_dart().into_dart(),
            self.capabilities.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::ServerHello
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::ServerHello>
    for crate::api::network::ServerHello
{
    fn into_into_dart(self) -> crate::api::network::ServerHello {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::SharedLoanListResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.loans.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::SharedLoanListResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::SharedLoanListResult>
    for crate::api::network::SharedLoanListResult
{
    fn into_into_dart(self) -> crate::api::network::SharedLoanListResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::SharedLoanSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.loan_id.into_into_dart().into_dart(),
            self.lender_party_id.into_into_dart().into_dart(),
            self.borrower_party_id.into_into_dart().into_dart(),
            self.principal_minor.into_into_dart().into_dart(),
            self.currency.into_into_dart().into_dart(),
            self.currency_scale.into_into_dart().into_dart(),
            self.lifecycle.into_into_dart().into_dart(),
            self.loan_date.into_into_dart().into_dart(),
            self.maturity_date.into_into_dart().into_dart(),
            self.repayments.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::SharedLoanSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::SharedLoanSummary>
    for crate::api::network::SharedLoanSummary
{
    fn into_into_dart(self) -> crate::api::network::SharedLoanSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::network::SharedRepayment {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.event_type.into_into_dart().into_dart(),
            self.amount_minor.into_into_dart().into_dart(),
            self.currency.into_into_dart().into_dart(),
            self.currency_scale.into_into_dart().into_dart(),
            self.payment_date.into_into_dart().into_dart(),
            self.recorded_at.into_into_dart().into_dart(),
            self.payment_method.into_into_dart().into_dart(),
            self.reverses_event_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::network::SharedRepayment
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::network::SharedRepayment>
    for crate::api::network::SharedRepayment
{
    fn into_into_dart(self) -> crate::api::network::SharedRepayment {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::network::AccountBootstrap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <String>::sse_encode(self.user_id, serializer);
        <String>::sse_encode(self.workspace_id, serializer);
        <String>::sse_encode(self.self_party_id, serializer);
        <String>::sse_encode(self.phone_e164, serializer);
        <String>::sse_encode(self.preferred_language, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::network::AuthTokens {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <bool>::sse_encode(self.transport_unavailable, serializer);
        <String>::sse_encode(self.access_token, serializer);
        <String>::sse_encode(self.refresh_token, serializer);
        <String>::sse_encode(self.user_id, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::network::ChatCredentials {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <String>::sse_encode(self.jid, serializer);
        <String>::sse_encode(self.access_token, serializer);
        <i64>::sse_encode(self.expires_at_ms, serializer);
        <String>::sse_encode(self.websocket_url, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::network::LenderSearchResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <Vec<crate::api::network::PublicLender>>::sse_encode(self.lenders, serializer);
        <String>::sse_encode(self.next_after_id, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::network::PublicLender> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::network::PublicLender>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::network::SharedLoanSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::network::SharedLoanSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::network::SharedRepayment> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::network::SharedRepayment>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::network::MyLenderProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <Option<crate::api::network::PublicLender>>::sse_encode(self.profile, serializer);
        <bool>::sse_encode(self.published, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::network::NetworkResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::network::PublicLender> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::network::PublicLender>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::network::OtpChallenge {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <String>::sse_encode(self.challenge_id, serializer);
        <u32>::sse_encode(self.expires_in_seconds, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::network::PendingLoanInvitation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <String>::sse_encode(self.invitation_id, serializer);
        <bool>::sse_encode(self.linked_to_existing_account, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::network::PublicLender {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <String>::sse_encode(self.locality, serializer);
        <String>::sse_encode(self.city, serializer);
        <String>::sse_encode(self.postal_code, serializer);
        <String>::sse_encode(self.country_code, serializer);
        <i64>::sse_encode(self.minimum_loan_minor, serializer);
        <i64>::sse_encode(self.maximum_loan_minor, serializer);
        <String>::sse_encode(self.currency, serializer);
        <u32>::sse_encode(self.currency_scale, serializer);
        <Vec<String>>::sse_encode(self.categories, serializer);
        <String>::sse_encode(self.verification_level, serializer);
        <bool>::sse_encode(self.available, serializer);
        <String>::sse_encode(self.public_description, serializer);
    }
}

impl SseEncode for crate::api::network::ServerHello {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <u32>::sse_encode(self.protocol_major, serializer);
        <String>::sse_encode(self.server_build, serializer);
        <u32>::sse_encode(self.maximum_frame_bytes, serializer);
        <Vec<String>>::sse_encode(self.capabilities, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::network::SharedLoanListResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <Vec<crate::api::network::SharedLoanSummary>>::sse_encode(self.loans, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::api::network::SharedLoanSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.loan_id, serializer);
        <String>::sse_encode(self.lender_party_id, serializer);
        <String>::sse_encode(self.borrower_party_id, serializer);
        <i64>::sse_encode(self.principal_minor, serializer);
        <String>::sse_encode(self.currency, serializer);
        <u32>::sse_encode(self.currency_scale, serializer);
        <String>::sse_encode(self.lifecycle, serializer);
        <String>::sse_encode(self.loan_date, serializer);
        <String>::sse_encode(self.maturity_date, serializer);
        <Vec<crate::api::network::SharedRepayment>>::sse_encode(self.repayments, serializer);
    }
}

impl SseEncode for crate::api::network::SharedRepayment {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.event_type, serializer);
        <i64>::sse_encode(self.amount_minor, serializer);
        <String>::sse_encode(self.currency, serializer);
        <u32>::sse_encode(self.currency_scale, serializer);
        <String>::sse_encode(self.payment_date, serializer);
        <String>::sse_encode(self.recorded_at, serializer);
        <String>::sse_encode(self.payment_method, serializer);
        <String>::sse_encode(self.reverses_event_id, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
