// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/network.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1459718515;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_loanx',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<NetworkResult> crateApiNetworkBlockPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
  });

  Future<ServerHello> crateApiNetworkConnectAndHello({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String clientBuild,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<NetworkResult> crateApiNetworkLogoutSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  });

  Future<AuthTokens> crateApiNetworkRefreshSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String refreshToken,
  });

  Future<NetworkResult> crateApiNetworkReportPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
    required String reason,
  });

  Future<ChatCredentials> crateApiNetworkRequestChatCredentials({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  });

  Future<OtpChallenge> crateApiNetworkRequestOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String phoneE164,
  });

  Future<LenderSearchResult> crateApiNetworkSearchPublicLenders({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required int area,
    required String query,
    required int limit,
    required String afterId,
  });

  Future<NetworkResult> crateApiNetworkUpdateLanguage({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String preferredLanguage,
  });

  Future<AuthTokens> crateApiNetworkVerifyOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String challengeId,
    required String phoneE164,
    required String otp,
    required String preferredLanguage,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<NetworkResult> crateApiNetworkBlockPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkBlockPublicLenderConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          profileId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkBlockPublicLenderConstMeta =>
      const TaskConstMeta(
        debugName: "block_public_lender",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "profileId",
        ],
      );

  @override
  Future<ServerHello> crateApiNetworkConnectAndHello({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String clientBuild,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(clientBuild, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_server_hello,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkConnectAndHelloConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          clientBuild,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkConnectAndHelloConstMeta =>
      const TaskConstMeta(
        debugName: "connect_and_hello",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "clientBuild",
        ],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<NetworkResult> crateApiNetworkLogoutSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkLogoutSessionConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkLogoutSessionConstMeta =>
      const TaskConstMeta(
        debugName: "logout_session",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
        ],
      );

  @override
  Future<AuthTokens> crateApiNetworkRefreshSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String refreshToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(refreshToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_tokens,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkRefreshSessionConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          refreshToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRefreshSessionConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_session",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "refreshToken",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkReportPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
    required String reason,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(profileId, serializer);
          sse_encode_String(reason, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkReportPublicLenderConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          profileId,
          reason,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkReportPublicLenderConstMeta =>
      const TaskConstMeta(
        debugName: "report_public_lender",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "profileId",
          "reason",
        ],
      );

  @override
  Future<ChatCredentials> crateApiNetworkRequestChatCredentials({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_credentials,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkRequestChatCredentialsConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRequestChatCredentialsConstMeta =>
      const TaskConstMeta(
        debugName: "request_chat_credentials",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
        ],
      );

  @override
  Future<OtpChallenge> crateApiNetworkRequestOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String phoneE164,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(phoneE164, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_otp_challenge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkRequestOtpConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          phoneE164,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRequestOtpConstMeta => const TaskConstMeta(
    debugName: "request_otp",
    argNames: [
      "serverAddress",
      "serverName",
      "trustedCertificatePem",
      "deviceId",
      "phoneE164",
    ],
  );

  @override
  Future<LenderSearchResult> crateApiNetworkSearchPublicLenders({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required int area,
    required String query,
    required int limit,
    required String afterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_u_32(area, serializer);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_String(afterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lender_search_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkSearchPublicLendersConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          area,
          query,
          limit,
          afterId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSearchPublicLendersConstMeta =>
      const TaskConstMeta(
        debugName: "search_public_lenders",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "area",
          "query",
          "limit",
          "afterId",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkUpdateLanguage({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String preferredLanguage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(preferredLanguage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkUpdateLanguageConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          preferredLanguage,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkUpdateLanguageConstMeta =>
      const TaskConstMeta(
        debugName: "update_language",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "preferredLanguage",
        ],
      );

  @override
  Future<AuthTokens> crateApiNetworkVerifyOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String challengeId,
    required String phoneE164,
    required String otp,
    required String preferredLanguage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(challengeId, serializer);
          sse_encode_String(phoneE164, serializer);
          sse_encode_String(otp, serializer);
          sse_encode_String(preferredLanguage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_tokens,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkVerifyOtpConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          challengeId,
          phoneE164,
          otp,
          preferredLanguage,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkVerifyOtpConstMeta => const TaskConstMeta(
    debugName: "verify_otp",
    argNames: [
      "serverAddress",
      "serverName",
      "trustedCertificatePem",
      "deviceId",
      "challengeId",
      "phoneE164",
      "otp",
      "preferredLanguage",
    ],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthTokens dco_decode_auth_tokens(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AuthTokens(
      success: dco_decode_bool(arr[0]),
      accessToken: dco_decode_String(arr[1]),
      refreshToken: dco_decode_String(arr[2]),
      userId: dco_decode_String(arr[3]),
      errorMessage: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatCredentials dco_decode_chat_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ChatCredentials(
      success: dco_decode_bool(arr[0]),
      jid: dco_decode_String(arr[1]),
      accessToken: dco_decode_String(arr[2]),
      expiresAtMs: dco_decode_i_64(arr[3]),
      websocketUrl: dco_decode_String(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LenderSearchResult dco_decode_lender_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LenderSearchResult(
      success: dco_decode_bool(arr[0]),
      lenders: dco_decode_list_public_lender(arr[1]),
      nextAfterId: dco_decode_String(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<PublicLender> dco_decode_list_public_lender(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_public_lender).toList();
  }

  @protected
  NetworkResult dco_decode_network_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NetworkResult(
      success: dco_decode_bool(arr[0]),
      errorMessage: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  OtpChallenge dco_decode_otp_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OtpChallenge(
      success: dco_decode_bool(arr[0]),
      challengeId: dco_decode_String(arr[1]),
      expiresInSeconds: dco_decode_u_32(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  PublicLender dco_decode_public_lender(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return PublicLender(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      locality: dco_decode_String(arr[2]),
      city: dco_decode_String(arr[3]),
      postalCode: dco_decode_String(arr[4]),
      countryCode: dco_decode_String(arr[5]),
      minimumLoanMinor: dco_decode_i_64(arr[6]),
      maximumLoanMinor: dco_decode_i_64(arr[7]),
      currency: dco_decode_String(arr[8]),
      currencyScale: dco_decode_u_32(arr[9]),
      categories: dco_decode_list_String(arr[10]),
      verificationLevel: dco_decode_String(arr[11]),
      publicDescription: dco_decode_String(arr[12]),
    );
  }

  @protected
  ServerHello dco_decode_server_hello(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ServerHello(
      success: dco_decode_bool(arr[0]),
      protocolMajor: dco_decode_u_32(arr[1]),
      serverBuild: dco_decode_String(arr[2]),
      maximumFrameBytes: dco_decode_u_32(arr[3]),
      capabilities: dco_decode_list_String(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthTokens sse_decode_auth_tokens(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return AuthTokens(
      success: var_success,
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
      userId: var_userId,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChatCredentials sse_decode_chat_credentials(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_jid = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_expiresAtMs = sse_decode_i_64(deserializer);
    var var_websocketUrl = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return ChatCredentials(
      success: var_success,
      jid: var_jid,
      accessToken: var_accessToken,
      expiresAtMs: var_expiresAtMs,
      websocketUrl: var_websocketUrl,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LenderSearchResult sse_decode_lender_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_lenders = sse_decode_list_public_lender(deserializer);
    var var_nextAfterId = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return LenderSearchResult(
      success: var_success,
      lenders: var_lenders,
      nextAfterId: var_nextAfterId,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<PublicLender> sse_decode_list_public_lender(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PublicLender>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_public_lender(deserializer));
    }
    return ans_;
  }

  @protected
  NetworkResult sse_decode_network_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return NetworkResult(success: var_success, errorMessage: var_errorMessage);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OtpChallenge sse_decode_otp_challenge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_challengeId = sse_decode_String(deserializer);
    var var_expiresInSeconds = sse_decode_u_32(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return OtpChallenge(
      success: var_success,
      challengeId: var_challengeId,
      expiresInSeconds: var_expiresInSeconds,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  PublicLender sse_decode_public_lender(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_locality = sse_decode_String(deserializer);
    var var_city = sse_decode_String(deserializer);
    var var_postalCode = sse_decode_String(deserializer);
    var var_countryCode = sse_decode_String(deserializer);
    var var_minimumLoanMinor = sse_decode_i_64(deserializer);
    var var_maximumLoanMinor = sse_decode_i_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_currencyScale = sse_decode_u_32(deserializer);
    var var_categories = sse_decode_list_String(deserializer);
    var var_verificationLevel = sse_decode_String(deserializer);
    var var_publicDescription = sse_decode_String(deserializer);
    return PublicLender(
      id: var_id,
      displayName: var_displayName,
      locality: var_locality,
      city: var_city,
      postalCode: var_postalCode,
      countryCode: var_countryCode,
      minimumLoanMinor: var_minimumLoanMinor,
      maximumLoanMinor: var_maximumLoanMinor,
      currency: var_currency,
      currencyScale: var_currencyScale,
      categories: var_categories,
      verificationLevel: var_verificationLevel,
      publicDescription: var_publicDescription,
    );
  }

  @protected
  ServerHello sse_decode_server_hello(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_protocolMajor = sse_decode_u_32(deserializer);
    var var_serverBuild = sse_decode_String(deserializer);
    var var_maximumFrameBytes = sse_decode_u_32(deserializer);
    var var_capabilities = sse_decode_list_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return ServerHello(
      success: var_success,
      protocolMajor: var_protocolMajor,
      serverBuild: var_serverBuild,
      maximumFrameBytes: var_maximumFrameBytes,
      capabilities: var_capabilities,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_tokens(AuthTokens self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.refreshToken, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_chat_credentials(
    ChatCredentials self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.jid, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_i_64(self.expiresAtMs, serializer);
    sse_encode_String(self.websocketUrl, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_lender_search_result(
    LenderSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_list_public_lender(self.lenders, serializer);
    sse_encode_String(self.nextAfterId, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_public_lender(
    List<PublicLender> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_public_lender(item, serializer);
    }
  }

  @protected
  void sse_encode_network_result(NetworkResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_otp_challenge(OtpChallenge self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.challengeId, serializer);
    sse_encode_u_32(self.expiresInSeconds, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_public_lender(PublicLender self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.locality, serializer);
    sse_encode_String(self.city, serializer);
    sse_encode_String(self.postalCode, serializer);
    sse_encode_String(self.countryCode, serializer);
    sse_encode_i_64(self.minimumLoanMinor, serializer);
    sse_encode_i_64(self.maximumLoanMinor, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_u_32(self.currencyScale, serializer);
    sse_encode_list_String(self.categories, serializer);
    sse_encode_String(self.verificationLevel, serializer);
    sse_encode_String(self.publicDescription, serializer);
  }

  @protected
  void sse_encode_server_hello(ServerHello self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_u_32(self.protocolMajor, serializer);
    sse_encode_String(self.serverBuild, serializer);
    sse_encode_u_32(self.maximumFrameBytes, serializer);
    sse_encode_list_String(self.capabilities, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
