// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/network.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountBootstrap dco_decode_account_bootstrap(dynamic raw);

  @protected
  AuthTokens dco_decode_auth_tokens(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PublicLender dco_decode_box_autoadd_public_lender(dynamic raw);

  @protected
  ChatCredentials dco_decode_chat_credentials(dynamic raw);

  @protected
  ContactOtpVerification dco_decode_contact_otp_verification(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LenderSearchResult dco_decode_lender_search_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PublicLender> dco_decode_list_public_lender(dynamic raw);

  @protected
  List<SharedLoanSummary> dco_decode_list_shared_loan_summary(dynamic raw);

  @protected
  List<SharedRepayment> dco_decode_list_shared_repayment(dynamic raw);

  @protected
  List<SyncChange> dco_decode_list_sync_change(dynamic raw);

  @protected
  MyLenderProfile dco_decode_my_lender_profile(dynamic raw);

  @protected
  NetworkResult dco_decode_network_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PublicLender? dco_decode_opt_box_autoadd_public_lender(dynamic raw);

  @protected
  OtpChallenge dco_decode_otp_challenge(dynamic raw);

  @protected
  PendingLoanInvitation dco_decode_pending_loan_invitation(dynamic raw);

  @protected
  PublicLender dco_decode_public_lender(dynamic raw);

  @protected
  PullChangesResult dco_decode_pull_changes_result(dynamic raw);

  @protected
  ServerHello dco_decode_server_hello(dynamic raw);

  @protected
  SharedLoanListResult dco_decode_shared_loan_list_result(dynamic raw);

  @protected
  SharedLoanSummary dco_decode_shared_loan_summary(dynamic raw);

  @protected
  SharedRepayment dco_decode_shared_repayment(dynamic raw);

  @protected
  SyncChange dco_decode_sync_change(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VerifiedLoanResult dco_decode_verified_loan_result(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountBootstrap sse_decode_account_bootstrap(SseDeserializer deserializer);

  @protected
  AuthTokens sse_decode_auth_tokens(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PublicLender sse_decode_box_autoadd_public_lender(
    SseDeserializer deserializer,
  );

  @protected
  ChatCredentials sse_decode_chat_credentials(SseDeserializer deserializer);

  @protected
  ContactOtpVerification sse_decode_contact_otp_verification(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LenderSearchResult sse_decode_lender_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PublicLender> sse_decode_list_public_lender(
    SseDeserializer deserializer,
  );

  @protected
  List<SharedLoanSummary> sse_decode_list_shared_loan_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<SharedRepayment> sse_decode_list_shared_repayment(
    SseDeserializer deserializer,
  );

  @protected
  List<SyncChange> sse_decode_list_sync_change(SseDeserializer deserializer);

  @protected
  MyLenderProfile sse_decode_my_lender_profile(SseDeserializer deserializer);

  @protected
  NetworkResult sse_decode_network_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PublicLender? sse_decode_opt_box_autoadd_public_lender(
    SseDeserializer deserializer,
  );

  @protected
  OtpChallenge sse_decode_otp_challenge(SseDeserializer deserializer);

  @protected
  PendingLoanInvitation sse_decode_pending_loan_invitation(
    SseDeserializer deserializer,
  );

  @protected
  PublicLender sse_decode_public_lender(SseDeserializer deserializer);

  @protected
  PullChangesResult sse_decode_pull_changes_result(
    SseDeserializer deserializer,
  );

  @protected
  ServerHello sse_decode_server_hello(SseDeserializer deserializer);

  @protected
  SharedLoanListResult sse_decode_shared_loan_list_result(
    SseDeserializer deserializer,
  );

  @protected
  SharedLoanSummary sse_decode_shared_loan_summary(
    SseDeserializer deserializer,
  );

  @protected
  SharedRepayment sse_decode_shared_repayment(SseDeserializer deserializer);

  @protected
  SyncChange sse_decode_sync_change(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VerifiedLoanResult sse_decode_verified_loan_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_bootstrap(
    AccountBootstrap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_tokens(AuthTokens self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_public_lender(
    PublicLender self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_credentials(
    ChatCredentials self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_otp_verification(
    ContactOtpVerification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_lender_search_result(
    LenderSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_public_lender(
    List<PublicLender> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shared_loan_summary(
    List<SharedLoanSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shared_repayment(
    List<SharedRepayment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_change(
    List<SyncChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_my_lender_profile(
    MyLenderProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_result(NetworkResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_public_lender(
    PublicLender? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_otp_challenge(OtpChallenge self, SseSerializer serializer);

  @protected
  void sse_encode_pending_loan_invitation(
    PendingLoanInvitation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_public_lender(PublicLender self, SseSerializer serializer);

  @protected
  void sse_encode_pull_changes_result(
    PullChangesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_hello(ServerHello self, SseSerializer serializer);

  @protected
  void sse_encode_shared_loan_list_result(
    SharedLoanListResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shared_loan_summary(
    SharedLoanSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shared_repayment(
    SharedRepayment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_change(SyncChange self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verified_loan_result(
    VerifiedLoanResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
