// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/network.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1565883145;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_loanx',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AccountBootstrap> crateApiNetworkAccountBootstrap({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  });

  Future<NetworkResult> crateApiNetworkBlockPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
  });

  Future<ServerHello> crateApiNetworkConnectAndHello({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String clientBuild,
  });

  Future<PendingLoanInvitation> crateApiNetworkCreatePendingLoan({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String borrowerPhoneE164,
    required String borrowerName,
    required List<int> loanPayloadJson,
  });

  Future<VerifiedLoanResult> crateApiNetworkCreateVerifiedLoan({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String verificationId,
    required String borrowerPartyId,
    required String borrowerName,
    required String borrowerEmail,
    required String borrowerCountryCode,
    required List<int> loanPayloadJson,
  });

  Future<void> crateApiSimpleInitApp();

  Future<SharedLoanListResult> crateApiNetworkListSharedLoans({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required int limit,
  });

  Future<NetworkResult> crateApiNetworkLogoutSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  });

  Future<MyLenderProfile> crateApiNetworkMyLenderProfile({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  });

  Future<NetworkResult> crateApiNetworkPublishPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String displayName,
    required String locality,
    required String city,
    required String postalCode,
    required String countryCode,
    required String minimumLoanMinor,
    required String maximumLoanMinor,
    required String currency,
    required int currencyScale,
    required List<String> categories,
    required bool available,
    required bool published,
    required String publicDescription,
  });

  Future<PullChangesResult> crateApiNetworkPullChanges({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required PlatformInt64 afterSequence,
    required int limit,
  });

  Future<NetworkResult> crateApiNetworkPushFinancialEvent({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String loanId,
    required String eventType,
    required String amountMinor,
    required String currency,
    required int currencyScale,
    required String effectiveDate,
    String? paymentMethod,
    String? referenceNumber,
    String? reversesEventId,
    String? reason,
    String? principalMinor,
    String? loanDate,
  });

  Future<NetworkResult> crateApiNetworkPushMutation({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String entityType,
    required String entityId,
    required String operation,
    required PlatformInt64 expectedRevision,
    required List<int> payloadJson,
  });

  Future<AuthTokens> crateApiNetworkRefreshSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String refreshToken,
  });

  Future<NetworkResult> crateApiNetworkReportPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
    required String reason,
  });

  Future<ChatCredentials> crateApiNetworkRequestChatCredentials({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  });

  Future<OtpChallenge> crateApiNetworkRequestOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String phoneE164,
  });

  Future<LenderSearchResult> crateApiNetworkSearchPublicLenders({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required int area,
    required String query,
    required int limit,
    required String afterId,
  });

  Future<NetworkResult> crateApiNetworkUpdateLanguage({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String preferredLanguage,
  });

  Future<ContactOtpVerification> crateApiNetworkVerifyContactOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String challengeId,
    required String phoneE164,
    required String otp,
  });

  Future<AuthTokens> crateApiNetworkVerifyOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String challengeId,
    required String phoneE164,
    required String otp,
    required String preferredLanguage,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AccountBootstrap> crateApiNetworkAccountBootstrap({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_bootstrap,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkAccountBootstrapConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkAccountBootstrapConstMeta =>
      const TaskConstMeta(
        debugName: "account_bootstrap",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkBlockPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkBlockPublicLenderConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          profileId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkBlockPublicLenderConstMeta =>
      const TaskConstMeta(
        debugName: "block_public_lender",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "profileId",
        ],
      );

  @override
  Future<ServerHello> crateApiNetworkConnectAndHello({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String clientBuild,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(clientBuild, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_server_hello,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkConnectAndHelloConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          clientBuild,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkConnectAndHelloConstMeta =>
      const TaskConstMeta(
        debugName: "connect_and_hello",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "clientBuild",
        ],
      );

  @override
  Future<PendingLoanInvitation> crateApiNetworkCreatePendingLoan({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String borrowerPhoneE164,
    required String borrowerName,
    required List<int> loanPayloadJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(operationId, serializer);
          sse_encode_String(borrowerPhoneE164, serializer);
          sse_encode_String(borrowerName, serializer);
          sse_encode_list_prim_u_8_loose(loanPayloadJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pending_loan_invitation,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkCreatePendingLoanConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          workspaceId,
          operationId,
          borrowerPhoneE164,
          borrowerName,
          loanPayloadJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkCreatePendingLoanConstMeta =>
      const TaskConstMeta(
        debugName: "create_pending_loan",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "workspaceId",
          "operationId",
          "borrowerPhoneE164",
          "borrowerName",
          "loanPayloadJson",
        ],
      );

  @override
  Future<VerifiedLoanResult> crateApiNetworkCreateVerifiedLoan({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String verificationId,
    required String borrowerPartyId,
    required String borrowerName,
    required String borrowerEmail,
    required String borrowerCountryCode,
    required List<int> loanPayloadJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(operationId, serializer);
          sse_encode_String(verificationId, serializer);
          sse_encode_String(borrowerPartyId, serializer);
          sse_encode_String(borrowerName, serializer);
          sse_encode_String(borrowerEmail, serializer);
          sse_encode_String(borrowerCountryCode, serializer);
          sse_encode_list_prim_u_8_loose(loanPayloadJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_verified_loan_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkCreateVerifiedLoanConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          workspaceId,
          operationId,
          verificationId,
          borrowerPartyId,
          borrowerName,
          borrowerEmail,
          borrowerCountryCode,
          loanPayloadJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkCreateVerifiedLoanConstMeta =>
      const TaskConstMeta(
        debugName: "create_verified_loan",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "workspaceId",
          "operationId",
          "verificationId",
          "borrowerPartyId",
          "borrowerName",
          "borrowerEmail",
          "borrowerCountryCode",
          "loanPayloadJson",
        ],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<SharedLoanListResult> crateApiNetworkListSharedLoans({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_shared_loan_list_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkListSharedLoansConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          limit,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkListSharedLoansConstMeta =>
      const TaskConstMeta(
        debugName: "list_shared_loans",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "limit",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkLogoutSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkLogoutSessionConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkLogoutSessionConstMeta =>
      const TaskConstMeta(
        debugName: "logout_session",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
        ],
      );

  @override
  Future<MyLenderProfile> crateApiNetworkMyLenderProfile({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_my_lender_profile,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkMyLenderProfileConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkMyLenderProfileConstMeta =>
      const TaskConstMeta(
        debugName: "my_lender_profile",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkPublishPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String displayName,
    required String locality,
    required String city,
    required String postalCode,
    required String countryCode,
    required String minimumLoanMinor,
    required String maximumLoanMinor,
    required String currency,
    required int currencyScale,
    required List<String> categories,
    required bool available,
    required bool published,
    required String publicDescription,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(displayName, serializer);
          sse_encode_String(locality, serializer);
          sse_encode_String(city, serializer);
          sse_encode_String(postalCode, serializer);
          sse_encode_String(countryCode, serializer);
          sse_encode_String(minimumLoanMinor, serializer);
          sse_encode_String(maximumLoanMinor, serializer);
          sse_encode_String(currency, serializer);
          sse_encode_u_32(currencyScale, serializer);
          sse_encode_list_String(categories, serializer);
          sse_encode_bool(available, serializer);
          sse_encode_bool(published, serializer);
          sse_encode_String(publicDescription, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkPublishPublicLenderConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          displayName,
          locality,
          city,
          postalCode,
          countryCode,
          minimumLoanMinor,
          maximumLoanMinor,
          currency,
          currencyScale,
          categories,
          available,
          published,
          publicDescription,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkPublishPublicLenderConstMeta =>
      const TaskConstMeta(
        debugName: "publish_public_lender",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "displayName",
          "locality",
          "city",
          "postalCode",
          "countryCode",
          "minimumLoanMinor",
          "maximumLoanMinor",
          "currency",
          "currencyScale",
          "categories",
          "available",
          "published",
          "publicDescription",
        ],
      );

  @override
  Future<PullChangesResult> crateApiNetworkPullChanges({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required PlatformInt64 afterSequence,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(workspaceId, serializer);
          sse_encode_i_64(afterSequence, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pull_changes_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkPullChangesConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          workspaceId,
          afterSequence,
          limit,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkPullChangesConstMeta => const TaskConstMeta(
    debugName: "pull_changes",
    argNames: [
      "serverAddress",
      "serverName",
      "trustedCertificatePem",
      "deviceId",
      "accessToken",
      "workspaceId",
      "afterSequence",
      "limit",
    ],
  );

  @override
  Future<NetworkResult> crateApiNetworkPushFinancialEvent({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String loanId,
    required String eventType,
    required String amountMinor,
    required String currency,
    required int currencyScale,
    required String effectiveDate,
    String? paymentMethod,
    String? referenceNumber,
    String? reversesEventId,
    String? reason,
    String? principalMinor,
    String? loanDate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(operationId, serializer);
          sse_encode_String(loanId, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_String(amountMinor, serializer);
          sse_encode_String(currency, serializer);
          sse_encode_u_32(currencyScale, serializer);
          sse_encode_String(effectiveDate, serializer);
          sse_encode_opt_String(paymentMethod, serializer);
          sse_encode_opt_String(referenceNumber, serializer);
          sse_encode_opt_String(reversesEventId, serializer);
          sse_encode_opt_String(reason, serializer);
          sse_encode_opt_String(principalMinor, serializer);
          sse_encode_opt_String(loanDate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkPushFinancialEventConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          workspaceId,
          operationId,
          loanId,
          eventType,
          amountMinor,
          currency,
          currencyScale,
          effectiveDate,
          paymentMethod,
          referenceNumber,
          reversesEventId,
          reason,
          principalMinor,
          loanDate,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkPushFinancialEventConstMeta =>
      const TaskConstMeta(
        debugName: "push_financial_event",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "workspaceId",
          "operationId",
          "loanId",
          "eventType",
          "amountMinor",
          "currency",
          "currencyScale",
          "effectiveDate",
          "paymentMethod",
          "referenceNumber",
          "reversesEventId",
          "reason",
          "principalMinor",
          "loanDate",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkPushMutation({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String workspaceId,
    required String operationId,
    required String entityType,
    required String entityId,
    required String operation,
    required PlatformInt64 expectedRevision,
    required List<int> payloadJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(operationId, serializer);
          sse_encode_String(entityType, serializer);
          sse_encode_String(entityId, serializer);
          sse_encode_String(operation, serializer);
          sse_encode_i_64(expectedRevision, serializer);
          sse_encode_list_prim_u_8_loose(payloadJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkPushMutationConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          workspaceId,
          operationId,
          entityType,
          entityId,
          operation,
          expectedRevision,
          payloadJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkPushMutationConstMeta =>
      const TaskConstMeta(
        debugName: "push_mutation",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "workspaceId",
          "operationId",
          "entityType",
          "entityId",
          "operation",
          "expectedRevision",
          "payloadJson",
        ],
      );

  @override
  Future<AuthTokens> crateApiNetworkRefreshSession({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String refreshToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(refreshToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_tokens,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkRefreshSessionConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          refreshToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRefreshSessionConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_session",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "refreshToken",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkReportPublicLender({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String profileId,
    required String reason,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(profileId, serializer);
          sse_encode_String(reason, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkReportPublicLenderConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          profileId,
          reason,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkReportPublicLenderConstMeta =>
      const TaskConstMeta(
        debugName: "report_public_lender",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "profileId",
          "reason",
        ],
      );

  @override
  Future<ChatCredentials> crateApiNetworkRequestChatCredentials({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_credentials,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkRequestChatCredentialsConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRequestChatCredentialsConstMeta =>
      const TaskConstMeta(
        debugName: "request_chat_credentials",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
        ],
      );

  @override
  Future<OtpChallenge> crateApiNetworkRequestOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String phoneE164,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(phoneE164, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_otp_challenge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkRequestOtpConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          phoneE164,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRequestOtpConstMeta => const TaskConstMeta(
    debugName: "request_otp",
    argNames: [
      "serverAddress",
      "serverName",
      "trustedCertificatePem",
      "deviceId",
      "phoneE164",
    ],
  );

  @override
  Future<LenderSearchResult> crateApiNetworkSearchPublicLenders({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required int area,
    required String query,
    required int limit,
    required String afterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_u_32(area, serializer);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_String(afterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lender_search_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkSearchPublicLendersConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          area,
          query,
          limit,
          afterId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSearchPublicLendersConstMeta =>
      const TaskConstMeta(
        debugName: "search_public_lenders",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "area",
          "query",
          "limit",
          "afterId",
        ],
      );

  @override
  Future<NetworkResult> crateApiNetworkUpdateLanguage({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String preferredLanguage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(preferredLanguage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkUpdateLanguageConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          preferredLanguage,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkUpdateLanguageConstMeta =>
      const TaskConstMeta(
        debugName: "update_language",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "preferredLanguage",
        ],
      );

  @override
  Future<ContactOtpVerification> crateApiNetworkVerifyContactOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String accessToken,
    required String challengeId,
    required String phoneE164,
    required String otp,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(challengeId, serializer);
          sse_encode_String(phoneE164, serializer);
          sse_encode_String(otp, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_contact_otp_verification,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkVerifyContactOtpConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          accessToken,
          challengeId,
          phoneE164,
          otp,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkVerifyContactOtpConstMeta =>
      const TaskConstMeta(
        debugName: "verify_contact_otp",
        argNames: [
          "serverAddress",
          "serverName",
          "trustedCertificatePem",
          "deviceId",
          "accessToken",
          "challengeId",
          "phoneE164",
          "otp",
        ],
      );

  @override
  Future<AuthTokens> crateApiNetworkVerifyOtp({
    required String serverAddress,
    required String serverName,
    required String trustedCertificatePem,
    required String deviceId,
    required String challengeId,
    required String phoneE164,
    required String otp,
    required String preferredLanguage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverAddress, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(trustedCertificatePem, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(challengeId, serializer);
          sse_encode_String(phoneE164, serializer);
          sse_encode_String(otp, serializer);
          sse_encode_String(preferredLanguage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_tokens,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkVerifyOtpConstMeta,
        argValues: [
          serverAddress,
          serverName,
          trustedCertificatePem,
          deviceId,
          challengeId,
          phoneE164,
          otp,
          preferredLanguage,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkVerifyOtpConstMeta => const TaskConstMeta(
    debugName: "verify_otp",
    argNames: [
      "serverAddress",
      "serverName",
      "trustedCertificatePem",
      "deviceId",
      "challengeId",
      "phoneE164",
      "otp",
      "preferredLanguage",
    ],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountBootstrap dco_decode_account_bootstrap(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AccountBootstrap(
      success: dco_decode_bool(arr[0]),
      userId: dco_decode_String(arr[1]),
      workspaceId: dco_decode_String(arr[2]),
      selfPartyId: dco_decode_String(arr[3]),
      phoneE164: dco_decode_String(arr[4]),
      preferredLanguage: dco_decode_String(arr[5]),
      errorMessage: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  AuthTokens dco_decode_auth_tokens(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AuthTokens(
      success: dco_decode_bool(arr[0]),
      transportUnavailable: dco_decode_bool(arr[1]),
      accessToken: dco_decode_String(arr[2]),
      refreshToken: dco_decode_String(arr[3]),
      userId: dco_decode_String(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PublicLender dco_decode_box_autoadd_public_lender(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_public_lender(raw);
  }

  @protected
  ChatCredentials dco_decode_chat_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ChatCredentials(
      success: dco_decode_bool(arr[0]),
      jid: dco_decode_String(arr[1]),
      accessToken: dco_decode_String(arr[2]),
      expiresAtMs: dco_decode_i_64(arr[3]),
      websocketUrl: dco_decode_String(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  ContactOtpVerification dco_decode_contact_otp_verification(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ContactOtpVerification(
      success: dco_decode_bool(arr[0]),
      verificationId: dco_decode_String(arr[1]),
      expiresInSeconds: dco_decode_u_32(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LenderSearchResult dco_decode_lender_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LenderSearchResult(
      success: dco_decode_bool(arr[0]),
      lenders: dco_decode_list_public_lender(arr[1]),
      nextAfterId: dco_decode_String(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<PublicLender> dco_decode_list_public_lender(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_public_lender).toList();
  }

  @protected
  List<SharedLoanSummary> dco_decode_list_shared_loan_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_shared_loan_summary).toList();
  }

  @protected
  List<SharedRepayment> dco_decode_list_shared_repayment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_shared_repayment).toList();
  }

  @protected
  List<SyncChange> dco_decode_list_sync_change(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sync_change).toList();
  }

  @protected
  MyLenderProfile dco_decode_my_lender_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MyLenderProfile(
      success: dco_decode_bool(arr[0]),
      profile: dco_decode_opt_box_autoadd_public_lender(arr[1]),
      published: dco_decode_bool(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  NetworkResult dco_decode_network_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NetworkResult(
      success: dco_decode_bool(arr[0]),
      errorMessage: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PublicLender? dco_decode_opt_box_autoadd_public_lender(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_public_lender(raw);
  }

  @protected
  OtpChallenge dco_decode_otp_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OtpChallenge(
      success: dco_decode_bool(arr[0]),
      challengeId: dco_decode_String(arr[1]),
      expiresInSeconds: dco_decode_u_32(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  PendingLoanInvitation dco_decode_pending_loan_invitation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PendingLoanInvitation(
      success: dco_decode_bool(arr[0]),
      invitationId: dco_decode_String(arr[1]),
      linkedToExistingAccount: dco_decode_bool(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  PublicLender dco_decode_public_lender(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return PublicLender(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      locality: dco_decode_String(arr[2]),
      city: dco_decode_String(arr[3]),
      postalCode: dco_decode_String(arr[4]),
      countryCode: dco_decode_String(arr[5]),
      minimumLoanMinor: dco_decode_i_64(arr[6]),
      maximumLoanMinor: dco_decode_i_64(arr[7]),
      currency: dco_decode_String(arr[8]),
      currencyScale: dco_decode_u_32(arr[9]),
      categories: dco_decode_list_String(arr[10]),
      verificationLevel: dco_decode_String(arr[11]),
      available: dco_decode_bool(arr[12]),
      publicDescription: dco_decode_String(arr[13]),
    );
  }

  @protected
  PullChangesResult dco_decode_pull_changes_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PullChangesResult(
      success: dco_decode_bool(arr[0]),
      changes: dco_decode_list_sync_change(arr[1]),
      nextSequence: dco_decode_i_64(arr[2]),
      hasMore: dco_decode_bool(arr[3]),
      errorMessage: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  ServerHello dco_decode_server_hello(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ServerHello(
      success: dco_decode_bool(arr[0]),
      protocolMajor: dco_decode_u_32(arr[1]),
      serverBuild: dco_decode_String(arr[2]),
      maximumFrameBytes: dco_decode_u_32(arr[3]),
      capabilities: dco_decode_list_String(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  SharedLoanListResult dco_decode_shared_loan_list_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SharedLoanListResult(
      success: dco_decode_bool(arr[0]),
      loans: dco_decode_list_shared_loan_summary(arr[1]),
      errorMessage: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SharedLoanSummary dco_decode_shared_loan_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SharedLoanSummary(
      loanId: dco_decode_String(arr[0]),
      lenderPartyId: dco_decode_String(arr[1]),
      borrowerPartyId: dco_decode_String(arr[2]),
      principalMinor: dco_decode_i_64(arr[3]),
      currency: dco_decode_String(arr[4]),
      currencyScale: dco_decode_u_32(arr[5]),
      lifecycle: dco_decode_String(arr[6]),
      loanDate: dco_decode_String(arr[7]),
      maturityDate: dco_decode_String(arr[8]),
      repayments: dco_decode_list_shared_repayment(arr[9]),
    );
  }

  @protected
  SharedRepayment dco_decode_shared_repayment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SharedRepayment(
      id: dco_decode_String(arr[0]),
      eventType: dco_decode_String(arr[1]),
      amountMinor: dco_decode_i_64(arr[2]),
      currency: dco_decode_String(arr[3]),
      currencyScale: dco_decode_u_32(arr[4]),
      paymentDate: dco_decode_String(arr[5]),
      recordedAt: dco_decode_String(arr[6]),
      paymentMethod: dco_decode_String(arr[7]),
      reversesEventId: dco_decode_String(arr[8]),
    );
  }

  @protected
  SyncChange dco_decode_sync_change(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncChange(
      sequence: dco_decode_i_64(arr[0]),
      entityType: dco_decode_String(arr[1]),
      entityId: dco_decode_String(arr[2]),
      operation: dco_decode_String(arr[3]),
      entityRevision: dco_decode_i_64(arr[4]),
      payloadJson: dco_decode_list_prim_u_8_strict(arr[5]),
      createdAtMs: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VerifiedLoanResult dco_decode_verified_loan_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VerifiedLoanResult(
      success: dco_decode_bool(arr[0]),
      loanId: dco_decode_String(arr[1]),
      replayed: dco_decode_bool(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountBootstrap sse_decode_account_bootstrap(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_workspaceId = sse_decode_String(deserializer);
    var var_selfPartyId = sse_decode_String(deserializer);
    var var_phoneE164 = sse_decode_String(deserializer);
    var var_preferredLanguage = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return AccountBootstrap(
      success: var_success,
      userId: var_userId,
      workspaceId: var_workspaceId,
      selfPartyId: var_selfPartyId,
      phoneE164: var_phoneE164,
      preferredLanguage: var_preferredLanguage,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  AuthTokens sse_decode_auth_tokens(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_transportUnavailable = sse_decode_bool(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return AuthTokens(
      success: var_success,
      transportUnavailable: var_transportUnavailable,
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
      userId: var_userId,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PublicLender sse_decode_box_autoadd_public_lender(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_public_lender(deserializer));
  }

  @protected
  ChatCredentials sse_decode_chat_credentials(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_jid = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_expiresAtMs = sse_decode_i_64(deserializer);
    var var_websocketUrl = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return ChatCredentials(
      success: var_success,
      jid: var_jid,
      accessToken: var_accessToken,
      expiresAtMs: var_expiresAtMs,
      websocketUrl: var_websocketUrl,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  ContactOtpVerification sse_decode_contact_otp_verification(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_verificationId = sse_decode_String(deserializer);
    var var_expiresInSeconds = sse_decode_u_32(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return ContactOtpVerification(
      success: var_success,
      verificationId: var_verificationId,
      expiresInSeconds: var_expiresInSeconds,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LenderSearchResult sse_decode_lender_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_lenders = sse_decode_list_public_lender(deserializer);
    var var_nextAfterId = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return LenderSearchResult(
      success: var_success,
      lenders: var_lenders,
      nextAfterId: var_nextAfterId,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<PublicLender> sse_decode_list_public_lender(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PublicLender>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_public_lender(deserializer));
    }
    return ans_;
  }

  @protected
  List<SharedLoanSummary> sse_decode_list_shared_loan_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SharedLoanSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_shared_loan_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<SharedRepayment> sse_decode_list_shared_repayment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SharedRepayment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_shared_repayment(deserializer));
    }
    return ans_;
  }

  @protected
  List<SyncChange> sse_decode_list_sync_change(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SyncChange>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sync_change(deserializer));
    }
    return ans_;
  }

  @protected
  MyLenderProfile sse_decode_my_lender_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_profile = sse_decode_opt_box_autoadd_public_lender(deserializer);
    var var_published = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return MyLenderProfile(
      success: var_success,
      profile: var_profile,
      published: var_published,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  NetworkResult sse_decode_network_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return NetworkResult(success: var_success, errorMessage: var_errorMessage);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PublicLender? sse_decode_opt_box_autoadd_public_lender(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_public_lender(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OtpChallenge sse_decode_otp_challenge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_challengeId = sse_decode_String(deserializer);
    var var_expiresInSeconds = sse_decode_u_32(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return OtpChallenge(
      success: var_success,
      challengeId: var_challengeId,
      expiresInSeconds: var_expiresInSeconds,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  PendingLoanInvitation sse_decode_pending_loan_invitation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_invitationId = sse_decode_String(deserializer);
    var var_linkedToExistingAccount = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return PendingLoanInvitation(
      success: var_success,
      invitationId: var_invitationId,
      linkedToExistingAccount: var_linkedToExistingAccount,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  PublicLender sse_decode_public_lender(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_locality = sse_decode_String(deserializer);
    var var_city = sse_decode_String(deserializer);
    var var_postalCode = sse_decode_String(deserializer);
    var var_countryCode = sse_decode_String(deserializer);
    var var_minimumLoanMinor = sse_decode_i_64(deserializer);
    var var_maximumLoanMinor = sse_decode_i_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_currencyScale = sse_decode_u_32(deserializer);
    var var_categories = sse_decode_list_String(deserializer);
    var var_verificationLevel = sse_decode_String(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_publicDescription = sse_decode_String(deserializer);
    return PublicLender(
      id: var_id,
      displayName: var_displayName,
      locality: var_locality,
      city: var_city,
      postalCode: var_postalCode,
      countryCode: var_countryCode,
      minimumLoanMinor: var_minimumLoanMinor,
      maximumLoanMinor: var_maximumLoanMinor,
      currency: var_currency,
      currencyScale: var_currencyScale,
      categories: var_categories,
      verificationLevel: var_verificationLevel,
      available: var_available,
      publicDescription: var_publicDescription,
    );
  }

  @protected
  PullChangesResult sse_decode_pull_changes_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_changes = sse_decode_list_sync_change(deserializer);
    var var_nextSequence = sse_decode_i_64(deserializer);
    var var_hasMore = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return PullChangesResult(
      success: var_success,
      changes: var_changes,
      nextSequence: var_nextSequence,
      hasMore: var_hasMore,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  ServerHello sse_decode_server_hello(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_protocolMajor = sse_decode_u_32(deserializer);
    var var_serverBuild = sse_decode_String(deserializer);
    var var_maximumFrameBytes = sse_decode_u_32(deserializer);
    var var_capabilities = sse_decode_list_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return ServerHello(
      success: var_success,
      protocolMajor: var_protocolMajor,
      serverBuild: var_serverBuild,
      maximumFrameBytes: var_maximumFrameBytes,
      capabilities: var_capabilities,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  SharedLoanListResult sse_decode_shared_loan_list_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_loans = sse_decode_list_shared_loan_summary(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return SharedLoanListResult(
      success: var_success,
      loans: var_loans,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  SharedLoanSummary sse_decode_shared_loan_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loanId = sse_decode_String(deserializer);
    var var_lenderPartyId = sse_decode_String(deserializer);
    var var_borrowerPartyId = sse_decode_String(deserializer);
    var var_principalMinor = sse_decode_i_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_currencyScale = sse_decode_u_32(deserializer);
    var var_lifecycle = sse_decode_String(deserializer);
    var var_loanDate = sse_decode_String(deserializer);
    var var_maturityDate = sse_decode_String(deserializer);
    var var_repayments = sse_decode_list_shared_repayment(deserializer);
    return SharedLoanSummary(
      loanId: var_loanId,
      lenderPartyId: var_lenderPartyId,
      borrowerPartyId: var_borrowerPartyId,
      principalMinor: var_principalMinor,
      currency: var_currency,
      currencyScale: var_currencyScale,
      lifecycle: var_lifecycle,
      loanDate: var_loanDate,
      maturityDate: var_maturityDate,
      repayments: var_repayments,
    );
  }

  @protected
  SharedRepayment sse_decode_shared_repayment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_eventType = sse_decode_String(deserializer);
    var var_amountMinor = sse_decode_i_64(deserializer);
    var var_currency = sse_decode_String(deserializer);
    var var_currencyScale = sse_decode_u_32(deserializer);
    var var_paymentDate = sse_decode_String(deserializer);
    var var_recordedAt = sse_decode_String(deserializer);
    var var_paymentMethod = sse_decode_String(deserializer);
    var var_reversesEventId = sse_decode_String(deserializer);
    return SharedRepayment(
      id: var_id,
      eventType: var_eventType,
      amountMinor: var_amountMinor,
      currency: var_currency,
      currencyScale: var_currencyScale,
      paymentDate: var_paymentDate,
      recordedAt: var_recordedAt,
      paymentMethod: var_paymentMethod,
      reversesEventId: var_reversesEventId,
    );
  }

  @protected
  SyncChange sse_decode_sync_change(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sequence = sse_decode_i_64(deserializer);
    var var_entityType = sse_decode_String(deserializer);
    var var_entityId = sse_decode_String(deserializer);
    var var_operation = sse_decode_String(deserializer);
    var var_entityRevision = sse_decode_i_64(deserializer);
    var var_payloadJson = sse_decode_list_prim_u_8_strict(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    return SyncChange(
      sequence: var_sequence,
      entityType: var_entityType,
      entityId: var_entityId,
      operation: var_operation,
      entityRevision: var_entityRevision,
      payloadJson: var_payloadJson,
      createdAtMs: var_createdAtMs,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VerifiedLoanResult sse_decode_verified_loan_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_loanId = sse_decode_String(deserializer);
    var var_replayed = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return VerifiedLoanResult(
      success: var_success,
      loanId: var_loanId,
      replayed: var_replayed,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_bootstrap(
    AccountBootstrap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.workspaceId, serializer);
    sse_encode_String(self.selfPartyId, serializer);
    sse_encode_String(self.phoneE164, serializer);
    sse_encode_String(self.preferredLanguage, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_auth_tokens(AuthTokens self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_bool(self.transportUnavailable, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.refreshToken, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_public_lender(
    PublicLender self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_public_lender(self, serializer);
  }

  @protected
  void sse_encode_chat_credentials(
    ChatCredentials self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.jid, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_i_64(self.expiresAtMs, serializer);
    sse_encode_String(self.websocketUrl, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_contact_otp_verification(
    ContactOtpVerification self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.verificationId, serializer);
    sse_encode_u_32(self.expiresInSeconds, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_lender_search_result(
    LenderSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_list_public_lender(self.lenders, serializer);
    sse_encode_String(self.nextAfterId, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_public_lender(
    List<PublicLender> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_public_lender(item, serializer);
    }
  }

  @protected
  void sse_encode_list_shared_loan_summary(
    List<SharedLoanSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_shared_loan_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_shared_repayment(
    List<SharedRepayment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_shared_repayment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sync_change(
    List<SyncChange> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sync_change(item, serializer);
    }
  }

  @protected
  void sse_encode_my_lender_profile(
    MyLenderProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_box_autoadd_public_lender(self.profile, serializer);
    sse_encode_bool(self.published, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_network_result(NetworkResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_public_lender(
    PublicLender? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_public_lender(self, serializer);
    }
  }

  @protected
  void sse_encode_otp_challenge(OtpChallenge self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.challengeId, serializer);
    sse_encode_u_32(self.expiresInSeconds, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_pending_loan_invitation(
    PendingLoanInvitation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.invitationId, serializer);
    sse_encode_bool(self.linkedToExistingAccount, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_public_lender(PublicLender self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.locality, serializer);
    sse_encode_String(self.city, serializer);
    sse_encode_String(self.postalCode, serializer);
    sse_encode_String(self.countryCode, serializer);
    sse_encode_i_64(self.minimumLoanMinor, serializer);
    sse_encode_i_64(self.maximumLoanMinor, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_u_32(self.currencyScale, serializer);
    sse_encode_list_String(self.categories, serializer);
    sse_encode_String(self.verificationLevel, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_String(self.publicDescription, serializer);
  }

  @protected
  void sse_encode_pull_changes_result(
    PullChangesResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_list_sync_change(self.changes, serializer);
    sse_encode_i_64(self.nextSequence, serializer);
    sse_encode_bool(self.hasMore, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_server_hello(ServerHello self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_u_32(self.protocolMajor, serializer);
    sse_encode_String(self.serverBuild, serializer);
    sse_encode_u_32(self.maximumFrameBytes, serializer);
    sse_encode_list_String(self.capabilities, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_shared_loan_list_result(
    SharedLoanListResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_list_shared_loan_summary(self.loans, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_shared_loan_summary(
    SharedLoanSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.loanId, serializer);
    sse_encode_String(self.lenderPartyId, serializer);
    sse_encode_String(self.borrowerPartyId, serializer);
    sse_encode_i_64(self.principalMinor, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_u_32(self.currencyScale, serializer);
    sse_encode_String(self.lifecycle, serializer);
    sse_encode_String(self.loanDate, serializer);
    sse_encode_String(self.maturityDate, serializer);
    sse_encode_list_shared_repayment(self.repayments, serializer);
  }

  @protected
  void sse_encode_shared_repayment(
    SharedRepayment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.eventType, serializer);
    sse_encode_i_64(self.amountMinor, serializer);
    sse_encode_String(self.currency, serializer);
    sse_encode_u_32(self.currencyScale, serializer);
    sse_encode_String(self.paymentDate, serializer);
    sse_encode_String(self.recordedAt, serializer);
    sse_encode_String(self.paymentMethod, serializer);
    sse_encode_String(self.reversesEventId, serializer);
  }

  @protected
  void sse_encode_sync_change(SyncChange self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.sequence, serializer);
    sse_encode_String(self.entityType, serializer);
    sse_encode_String(self.entityId, serializer);
    sse_encode_String(self.operation, serializer);
    sse_encode_i_64(self.entityRevision, serializer);
    sse_encode_list_prim_u_8_strict(self.payloadJson, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verified_loan_result(
    VerifiedLoanResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.loanId, serializer);
    sse_encode_bool(self.replayed, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
