// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../v1.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'response.freezed.dart';

@freezed
sealed class Result with _$Result {
  const Result._();

  const factory Result.hello(HelloResponse field0) = Result_Hello;
  const factory Result.ping(PingResponse field0) = Result_Ping;
  const factory Result.error(ProtocolError field0) = Result_Error;
}
