import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PDFDemo extends StatelessWidget {
  const PDFDemo({super.key});

  void _printDocument() {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Text(
              'Hello, this is a PDF document generated by Flutter!',
            ),
          ); // Center
        },
      ),
    );

    Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('PDF Print Demo')),
      body: Center(
        child: ElevatedButton(
          onPressed: _printDocument,
          child: Text('Print PDF'),
        ),
      ),
    );
  }
}
