import 'package:intl_phone_number_input/intl_phone_number_input.dart';

class CountryConfig {
  const CountryConfig(
    this.code,
    this.alpha3Code,
    this.name,
    this.currency,
    this.symbol,
    this.dialCode,
  );
  final String code, alpha3Code, name, currency, symbol, dialCode;
  Country get phoneCountry => Country(
    name: name,
    alpha2Code: code,
    alpha3Code: alpha3Code,
    dialCode: dialCode,
  );
}

abstract final class CountryCatalog {
  static const all = <CountryConfig>[
    CountryConfig("AF", "AFG", "Afghanistan", "AFN", "؋", "+93"),
    CountryConfig("AL", "ALB", "Albania", "ALL", "L", "+355"),
    CountryConfig("DZ", "DZA", "Algeria", "DZD", "د.ج", "+213"),
    CountryConfig("AD", "AND", "Andorra", "EUR", "€", "+376"),
    CountryConfig("AO", "AGO", "Angola", "AOA", "Kz", "+244"),
    CountryConfig("AG", "ATG", "Antigua and Barbuda", "XCD", r"$", "+1268"),
    CountryConfig("AR", "ARG", "Argentina", "ARS", r"$", "+54"),
    CountryConfig("AM", "ARM", "Armenia", "AMD", "֏", "+374"),
    CountryConfig("AU", "AUS", "Australia", "AUD", r"$", "+61"),
    CountryConfig("AT", "AUT", "Austria", "EUR", "€", "+43"),
    CountryConfig("AZ", "AZE", "Azerbaijan", "AZN", "₼", "+994"),
    CountryConfig("BS", "BHS", "Bahamas", "BSD", r"$", "+1242"),
    CountryConfig("BH", "BHR", "Bahrain", "BHD", ".د.ب", "+973"),
    CountryConfig("BD", "BGD", "Bangladesh", "BDT", "৳", "+880"),
    CountryConfig("BB", "BRB", "Barbados", "BBD", r"$", "+1246"),
    CountryConfig("BY", "BLR", "Belarus", "BYN", "Br", "+375"),
    CountryConfig("BE", "BEL", "Belgium", "EUR", "€", "+32"),
    CountryConfig("BZ", "BLZ", "Belize", "BZD", r"$", "+501"),
    CountryConfig("BJ", "BEN", "Benin", "XOF", "Fr", "+229"),
    CountryConfig("BT", "BTN", "Bhutan", "BTN", "Nu.", "+975"),
    CountryConfig("BO", "BOL", "Bolivia", "BOB", "Bs.", "+591"),
    CountryConfig("BA", "BIH", "Bosnia and Herzegovina", "BAM", "KM", "+387"),
    CountryConfig("BW", "BWA", "Botswana", "BWP", "P", "+267"),
    CountryConfig("BR", "BRA", "Brazil", "BRL", r"R$", "+55"),
    CountryConfig("BN", "BRN", "Brunei", "BND", r"$", "+673"),
    CountryConfig("BG", "BGR", "Bulgaria", "BGN", "лв", "+359"),
    CountryConfig("BF", "BFA", "Burkina Faso", "XOF", "Fr", "+226"),
    CountryConfig("BI", "BDI", "Burundi", "BIF", "Fr", "+257"),
    CountryConfig("KH", "KHM", "Cambodia", "KHR", "៛", "+855"),
    CountryConfig("CM", "CMR", "Cameroon", "XAF", "Fr", "+237"),
    CountryConfig("CA", "CAN", "Canada", "CAD", r"$", "+1"),
    CountryConfig("CV", "CPV", "Cape Verde", "CVE", "Esc", "+238"),
    CountryConfig("CF", "CAF", "Central African Republic", "XAF", "Fr", "+236"),
    CountryConfig("TD", "TCD", "Chad", "XAF", "Fr", "+235"),
    CountryConfig("CL", "CHL", "Chile", "CLP", r"$", "+56"),
    CountryConfig("CN", "CHN", "China", "CNY", "¥", "+86"),
    CountryConfig("CO", "COL", "Colombia", "COP", r"$", "+57"),
    CountryConfig("KM", "COM", "Comoros", "KMF", "Fr", "+269"),
    CountryConfig("CR", "CRI", "Costa Rica", "CRC", "₡", "+506"),
    CountryConfig("HR", "HRV", "Croatia", "EUR", "€", "+385"),
    CountryConfig("CU", "CUB", "Cuba", "CUC", r"$", "+53"),
    CountryConfig("CY", "CYP", "Cyprus", "EUR", "€", "+357"),
    CountryConfig("CZ", "CZE", "Czechia", "CZK", "Kč", "+420"),
    CountryConfig("DK", "DNK", "Denmark", "DKK", "kr", "+45"),
    CountryConfig("DJ", "DJI", "Djibouti", "DJF", "Fr", "+253"),
    CountryConfig("DM", "DMA", "Dominica", "XCD", r"$", "+1767"),
    CountryConfig(
      "DO",
      "DOM",
      "Dominican Republic",
      "DOP",
      r"$",
      "+1809, 1829, 1849",
    ),
    CountryConfig("CD", "COD", "DR Congo", "CDF", "FC", "+243"),
    CountryConfig("EC", "ECU", "Ecuador", "USD", r"$", "+593"),
    CountryConfig("EG", "EGY", "Egypt", "EGP", "£", "+20"),
    CountryConfig("SV", "SLV", "El Salvador", "USD", r"$", "+503"),
    CountryConfig("GQ", "GNQ", "Equatorial Guinea", "XAF", "Fr", "+240"),
    CountryConfig("ER", "ERI", "Eritrea", "ERN", "Nfk", "+291"),
    CountryConfig("EE", "EST", "Estonia", "EUR", "€", "+372"),
    CountryConfig("SZ", "SWZ", "Eswatini", "SZL", "L", "+268"),
    CountryConfig("ET", "ETH", "Ethiopia", "ETB", "Br", "+251"),
    CountryConfig("FJ", "FJI", "Fiji", "FJD", r"$", "+679"),
    CountryConfig("FI", "FIN", "Finland", "EUR", "€", "+358"),
    CountryConfig("FR", "FRA", "France", "EUR", "€", "+33"),
    CountryConfig("GA", "GAB", "Gabon", "XAF", "Fr", "+241"),
    CountryConfig("GM", "GMB", "Gambia", "GMD", "D", "+220"),
    CountryConfig("GE", "GEO", "Georgia", "GEL", "₾", "+995"),
    CountryConfig("DE", "DEU", "Germany", "EUR", "€", "+49"),
    CountryConfig("GH", "GHA", "Ghana", "GHS", "₵", "+233"),
    CountryConfig("GR", "GRC", "Greece", "EUR", "€", "+30"),
    CountryConfig("GD", "GRD", "Grenada", "XCD", r"$", "+1473"),
    CountryConfig("GT", "GTM", "Guatemala", "GTQ", "Q", "+502"),
    CountryConfig("GN", "GIN", "Guinea", "GNF", "Fr", "+224"),
    CountryConfig("GW", "GNB", "Guinea-Bissau", "XOF", "Fr", "+245"),
    CountryConfig("GY", "GUY", "Guyana", "GYD", r"$", "+592"),
    CountryConfig("HT", "HTI", "Haiti", "HTG", "G", "+509"),
    CountryConfig("HN", "HND", "Honduras", "HNL", "L", "+504"),
    CountryConfig("HU", "HUN", "Hungary", "HUF", "Ft", "+36"),
    CountryConfig("IS", "ISL", "Iceland", "ISK", "kr", "+354"),
    CountryConfig("IN", "IND", "India", "INR", "₹", "+91"),
    CountryConfig("ID", "IDN", "Indonesia", "IDR", "Rp", "+62"),
    CountryConfig("IR", "IRN", "Iran", "IRR", "﷼", "+98"),
    CountryConfig("IQ", "IRQ", "Iraq", "IQD", "ع.د", "+964"),
    CountryConfig("IE", "IRL", "Ireland", "EUR", "€", "+353"),
    CountryConfig("IL", "ISR", "Israel", "ILS", "₪", "+972"),
    CountryConfig("IT", "ITA", "Italy", "EUR", "€", "+39"),
    CountryConfig("CI", "CIV", "Ivory Coast", "XOF", "Fr", "+225"),
    CountryConfig("JM", "JAM", "Jamaica", "JMD", r"$", "+1876"),
    CountryConfig("JP", "JPN", "Japan", "JPY", "¥", "+81"),
    CountryConfig("JO", "JOR", "Jordan", "JOD", "د.ا", "+962"),
    CountryConfig("KZ", "KAZ", "Kazakhstan", "KZT", "₸", "+7"),
    CountryConfig("KE", "KEN", "Kenya", "KES", "Sh", "+254"),
    CountryConfig("KI", "KIR", "Kiribati", "AUD", r"$", "+686"),
    CountryConfig("XK", "UNK", "Kosovo", "EUR", "€", "+383"),
    CountryConfig("KW", "KWT", "Kuwait", "KWD", "د.ك", "+965"),
    CountryConfig("KG", "KGZ", "Kyrgyzstan", "KGS", "с", "+996"),
    CountryConfig("LA", "LAO", "Laos", "LAK", "₭", "+856"),
    CountryConfig("LV", "LVA", "Latvia", "EUR", "€", "+371"),
    CountryConfig("LB", "LBN", "Lebanon", "LBP", "ل.ل", "+961"),
    CountryConfig("LS", "LSO", "Lesotho", "LSL", "L", "+266"),
    CountryConfig("LR", "LBR", "Liberia", "LRD", r"$", "+231"),
    CountryConfig("LY", "LBY", "Libya", "LYD", "ل.د", "+218"),
    CountryConfig("LI", "LIE", "Liechtenstein", "CHF", "Fr", "+423"),
    CountryConfig("LT", "LTU", "Lithuania", "EUR", "€", "+370"),
    CountryConfig("LU", "LUX", "Luxembourg", "EUR", "€", "+352"),
    CountryConfig("MG", "MDG", "Madagascar", "MGA", "Ar", "+261"),
    CountryConfig("MW", "MWI", "Malawi", "MWK", "MK", "+265"),
    CountryConfig("MY", "MYS", "Malaysia", "MYR", "RM", "+60"),
    CountryConfig("MV", "MDV", "Maldives", "MVR", ".ރ", "+960"),
    CountryConfig("ML", "MLI", "Mali", "XOF", "Fr", "+223"),
    CountryConfig("MT", "MLT", "Malta", "EUR", "€", "+356"),
    CountryConfig("MH", "MHL", "Marshall Islands", "USD", r"$", "+692"),
    CountryConfig("MR", "MRT", "Mauritania", "MRU", "UM", "+222"),
    CountryConfig("MU", "MUS", "Mauritius", "MUR", "₨", "+230"),
    CountryConfig("MX", "MEX", "Mexico", "MXN", r"$", "+52"),
    CountryConfig("FM", "FSM", "Micronesia", "USD", r"$", "+691"),
    CountryConfig("MD", "MDA", "Moldova", "MDL", "L", "+373"),
    CountryConfig("MC", "MCO", "Monaco", "EUR", "€", "+377"),
    CountryConfig("MN", "MNG", "Mongolia", "MNT", "₮", "+976"),
    CountryConfig("ME", "MNE", "Montenegro", "EUR", "€", "+382"),
    CountryConfig("MA", "MAR", "Morocco", "MAD", "د.م.", "+212"),
    CountryConfig("MZ", "MOZ", "Mozambique", "MZN", "MT", "+258"),
    CountryConfig("MM", "MMR", "Myanmar", "MMK", "Ks", "+95"),
    CountryConfig("NA", "NAM", "Namibia", "NAD", r"$", "+264"),
    CountryConfig("NR", "NRU", "Nauru", "AUD", r"$", "+674"),
    CountryConfig("NP", "NPL", "Nepal", "NPR", "₨", "+977"),
    CountryConfig("NL", "NLD", "Netherlands", "EUR", "€", "+31"),
    CountryConfig("NZ", "NZL", "New Zealand", "NZD", r"$", "+64"),
    CountryConfig("NI", "NIC", "Nicaragua", "NIO", r"C$", "+505"),
    CountryConfig("NE", "NER", "Niger", "XOF", "Fr", "+227"),
    CountryConfig("NG", "NGA", "Nigeria", "NGN", "₦", "+234"),
    CountryConfig("KP", "PRK", "North Korea", "KPW", "₩", "+850"),
    CountryConfig("MK", "MKD", "North Macedonia", "MKD", "den", "+389"),
    CountryConfig("NO", "NOR", "Norway", "NOK", "kr", "+47"),
    CountryConfig("OM", "OMN", "Oman", "OMR", "ر.ع.", "+968"),
    CountryConfig("PK", "PAK", "Pakistan", "PKR", "₨", "+92"),
    CountryConfig("PW", "PLW", "Palau", "USD", r"$", "+680"),
    CountryConfig("PA", "PAN", "Panama", "PAB", "B/.", "+507"),
    CountryConfig("PG", "PNG", "Papua New Guinea", "PGK", "K", "+675"),
    CountryConfig("PY", "PRY", "Paraguay", "PYG", "₲", "+595"),
    CountryConfig("PE", "PER", "Peru", "PEN", "S/ ", "+51"),
    CountryConfig("PH", "PHL", "Philippines", "PHP", "₱", "+63"),
    CountryConfig("PL", "POL", "Poland", "PLN", "zł", "+48"),
    CountryConfig("PT", "PRT", "Portugal", "EUR", "€", "+351"),
    CountryConfig("QA", "QAT", "Qatar", "QAR", "ر.ق", "+974"),
    CountryConfig("CG", "COG", "Republic of the Congo", "XAF", "Fr", "+242"),
    CountryConfig("RO", "ROU", "Romania", "RON", "lei", "+40"),
    CountryConfig("RU", "RUS", "Russia", "RUB", "₽", "+7"),
    CountryConfig("RW", "RWA", "Rwanda", "RWF", "Fr", "+250"),
    CountryConfig("KN", "KNA", "Saint Kitts and Nevis", "XCD", r"$", "+1869"),
    CountryConfig("LC", "LCA", "Saint Lucia", "XCD", r"$", "+1758"),
    CountryConfig(
      "VC",
      "VCT",
      "Saint Vincent and the Grenadines",
      "XCD",
      r"$",
      "+1784",
    ),
    CountryConfig("WS", "WSM", "Samoa", "WST", "T", "+685"),
    CountryConfig("SM", "SMR", "San Marino", "EUR", "€", "+378"),
    CountryConfig("ST", "STP", "São Tomé and Príncipe", "STN", "Db", "+239"),
    CountryConfig("SA", "SAU", "Saudi Arabia", "SAR", "ر.س", "+966"),
    CountryConfig("SN", "SEN", "Senegal", "XOF", "Fr", "+221"),
    CountryConfig("RS", "SRB", "Serbia", "RSD", "дин.", "+381"),
    CountryConfig("SC", "SYC", "Seychelles", "SCR", "₨", "+248"),
    CountryConfig("SL", "SLE", "Sierra Leone", "SLE", "Le", "+232"),
    CountryConfig("SG", "SGP", "Singapore", "SGD", r"$", "+65"),
    CountryConfig("SK", "SVK", "Slovakia", "EUR", "€", "+421"),
    CountryConfig("SI", "SVN", "Slovenia", "EUR", "€", "+386"),
    CountryConfig("SB", "SLB", "Solomon Islands", "SBD", r"$", "+677"),
    CountryConfig("SO", "SOM", "Somalia", "SOS", "Sh", "+252"),
    CountryConfig("ZA", "ZAF", "South Africa", "ZAR", "R", "+27"),
    CountryConfig("KR", "KOR", "South Korea", "KRW", "₩", "+82"),
    CountryConfig("SS", "SSD", "South Sudan", "SSP", "£", "+211"),
    CountryConfig("ES", "ESP", "Spain", "EUR", "€", "+34"),
    CountryConfig("LK", "LKA", "Sri Lanka", "LKR", "Rs  රු", "+94"),
    CountryConfig("SD", "SDN", "Sudan", "SDG", "ج.س", "+249"),
    CountryConfig("SR", "SUR", "Suriname", "SRD", r"$", "+597"),
    CountryConfig("SE", "SWE", "Sweden", "SEK", "kr", "+46"),
    CountryConfig("CH", "CHE", "Switzerland", "CHF", "Fr.", "+41"),
    CountryConfig("SY", "SYR", "Syria", "SYP", "£", "+963"),
    CountryConfig("TJ", "TJK", "Tajikistan", "TJS", "ЅМ", "+992"),
    CountryConfig("TZ", "TZA", "Tanzania", "TZS", "Sh", "+255"),
    CountryConfig("TH", "THA", "Thailand", "THB", "฿", "+66"),
    CountryConfig("TL", "TLS", "Timor-Leste", "USD", r"$", "+670"),
    CountryConfig("TG", "TGO", "Togo", "XOF", "Fr", "+228"),
    CountryConfig("TO", "TON", "Tonga", "TOP", r"T$", "+676"),
    CountryConfig("TT", "TTO", "Trinidad and Tobago", "TTD", r"$", "+1868"),
    CountryConfig("TN", "TUN", "Tunisia", "TND", "د.ت", "+216"),
    CountryConfig("TR", "TUR", "Turkey", "TRY", "₺", "+90"),
    CountryConfig("TM", "TKM", "Turkmenistan", "TMT", "m", "+993"),
    CountryConfig("TV", "TUV", "Tuvalu", "AUD", r"$", "+688"),
    CountryConfig("UG", "UGA", "Uganda", "UGX", "Sh", "+256"),
    CountryConfig("UA", "UKR", "Ukraine", "UAH", "₴", "+380"),
    CountryConfig("AE", "ARE", "United Arab Emirates", "AED", "د.إ", "+971"),
    CountryConfig("GB", "GBR", "United Kingdom", "GBP", "£", "+44"),
    CountryConfig("US", "USA", "United States", "USD", r"$", "+1"),
    CountryConfig("UY", "URY", "Uruguay", "UYU", r"$", "+598"),
    CountryConfig("UZ", "UZB", "Uzbekistan", "UZS", "so'm", "+998"),
    CountryConfig("VU", "VUT", "Vanuatu", "VUV", "Vt", "+678"),
    CountryConfig("VA", "VAT", "Vatican City", "EUR", "€", "+379"),
    CountryConfig("VE", "VEN", "Venezuela", "VES", "Bs.S.", "+58"),
    CountryConfig("VN", "VNM", "Vietnam", "VND", "₫", "+84"),
    CountryConfig("YE", "YEM", "Yemen", "YER", "﷼", "+967"),
    CountryConfig("ZM", "ZMB", "Zambia", "ZMW", "ZK", "+260"),
    CountryConfig("ZW", "ZWE", "Zimbabwe", "ZWL", r"$", "+263"),
    CountryConfig("AS", "ASM", "American Samoa", "USD", r"$", "+1684"),
    CountryConfig("AI", "AIA", "Anguilla", "XCD", r"$", "+1264"),
    CountryConfig("AQ", "ATA", "Antarctica", "USD", r"$", "+672"),
    CountryConfig("AW", "ABW", "Aruba", "AWG", "ƒ", "+297"),
    CountryConfig("BM", "BMU", "Bermuda", "BMD", r"$", "+1441"),
    CountryConfig(
      "IO",
      "IOT",
      "British Indian Ocean Territory",
      "USD",
      r"$",
      "+246",
    ),
    CountryConfig("VG", "VGB", "British Virgin Islands", "USD", r"$", "+1284"),
    CountryConfig("KY", "CYM", "Cayman Islands", "KYD", r"$", "+1345"),
    CountryConfig("CX", "CXR", "Christmas Island", "AUD", r"$", "+61"),
    CountryConfig("CC", "CCK", "Cocos Islands", "AUD", r"$", "+61"),
    CountryConfig("CK", "COK", "Cook Islands", "NZD", r"$", "+682"),
    CountryConfig("CW", "CUW", "Curacao", "XCG", "Cg", "+599"),
    CountryConfig("FK", "FLK", "Falkland Islands", "FKP", "£", "+500"),
    CountryConfig("FO", "FRO", "Faroe Islands", "DKK", "kr", "+298"),
    CountryConfig("PF", "PYF", "French Polynesia", "XPF", "₣", "+689"),
    CountryConfig("GI", "GIB", "Gibraltar", "GIP", "£", "+350"),
    CountryConfig("GL", "GRL", "Greenland", "DKK", "kr", "+299"),
    CountryConfig("GU", "GUM", "Guam", "USD", r"$", "+1671"),
    CountryConfig("GG", "GGY", "Guernsey", "GBP", "£", "+441481"),
    CountryConfig("HK", "HKG", "Hong Kong", "HKD", r"$", "+852"),
    CountryConfig("IM", "IMN", "Isle of Man", "GBP", "£", "+441624"),
    CountryConfig("JE", "JEY", "Jersey", "GBP", "£", "+441534"),
    CountryConfig("MO", "MAC", "Macau", "MOP", "P", "+853"),
    CountryConfig("YT", "MYT", "Mayotte", "EUR", "€", "+262"),
    CountryConfig("MS", "MSR", "Montserrat", "XCD", r"$", "+1664"),
    CountryConfig("AN", "ANT", "Netherlands Antilles", "XCG", "Cg", "+599"),
    CountryConfig("NC", "NCL", "New Caledonia", "XPF", "₣", "+687"),
    CountryConfig("NU", "NIU", "Niue", "NZD", r"$", "+683"),
    CountryConfig(
      "MP",
      "MNP",
      "Northern Mariana Islands",
      "USD",
      r"$",
      "+1670",
    ),
    CountryConfig("PS", "PSE", "Palestine", "ILS", "₪", "+970"),
    CountryConfig("PN", "PCN", "Pitcairn", "NZD", r"$", "+64"),
    CountryConfig("PR", "PRI", "Puerto Rico", "USD", r"$", "+1787, 1939"),
    CountryConfig("RE", "REU", "Reunion", "EUR", "€", "+262"),
    CountryConfig("BL", "BLM", "Saint Barthelemy", "EUR", "€", "+590"),
    CountryConfig("SH", "SHN", "Saint Helena", "SHP", "£", "+290"),
    CountryConfig("MF", "MAF", "Saint Martin", "EUR", "€", "+590"),
    CountryConfig("PM", "SPM", "Saint Pierre and Miquelon", "EUR", "€", "+508"),
    CountryConfig("SX", "SXM", "Sint Maarten", "XCG", "Cg", "+1721"),
    CountryConfig("SJ", "SJM", "Svalbard and Jan Mayen", "NOK", "kr", "+47"),
    CountryConfig("TW", "TWN", "Taiwan", "TWD", r"NT$", "+886"),
    CountryConfig("TK", "TKL", "Tokelau", "NZD", r"$", "+690"),
    CountryConfig(
      "TC",
      "TCA",
      "Turks and Caicos Islands",
      "USD",
      r"$",
      "+1649",
    ),
    CountryConfig("VI", "VIR", "U.S. Virgin Islands", "USD", r"$", "+1340"),
    CountryConfig("WF", "WLF", "Wallis and Futuna", "XPF", "₣", "+681"),
    CountryConfig("EH", "ESH", "Western Sahara", "MAD", "د.م.", "+212"),
  ];
  static final _byCode = {for (final c in all) c.code: c};
  static CountryConfig byCode(String? code) =>
      _byCode[code?.toUpperCase()] ?? _byCode['IN']!;
  static String e164(String? code, String number) =>
      byCode(code).dialCode + number.replaceAll(RegExp(r'[^0-9]'), '');
  static List<Country> get phoneCountries => all
      .where((c) => c.dialCode.length > 1)
      .map((c) => c.phoneCountry)
      .toList(growable: false);
}
