import 'dart:convert';
import 'dart:io';

const _sourceDirectory = 'lib/l10n';
const _keysOutputPath = 'lib/l10n/locale_keys.g.dart';
const _loaderOutputPath = 'lib/l10n/codegen_loader.g.dart';

void main() {
  final catalogs = <String, Map<String, dynamic>>{};
  for (final file in Directory(_sourceDirectory).listSync().whereType<File>()) {
    final match = RegExp(r'app_([A-Za-z_]+)\.arb$').firstMatch(file.path);
    if (match == null) continue;
    final contents = jsonDecode(file.readAsStringSync());
    if (contents is! Map<String, dynamic>) {
      throw FormatException('${file.path} must contain a JSON object.');
    }
    final locale = (contents['@@locale'] as String?) ?? match.group(1)!;
    catalogs[locale] = Map.of(contents)
      ..removeWhere((key, _) => key.startsWith('@'));
  }
  if (!catalogs.containsKey('en')) {
    throw const FormatException('lib/l10n/app_en.arb is required.');
  }

  _generateKeys(catalogs['en']!);
  _generateLoader(catalogs);
  stdout.writeln(
    'Generated ${catalogs['en']!.length} keys for ${catalogs.length} locales.',
  );
}

void _generateKeys(Map<String, dynamic> translations) {
  final identifiers = <String, String>{};
  final output = StringBuffer()
    ..writeln('// DO NOT EDIT. Generated by tool/generate_localizations.dart.')
    ..writeln()
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln()
    ..writeln('abstract final class LocaleKeys {');

  for (final key in translations.keys) {
    final baseIdentifier = _identifierFor(key);
    var identifier = baseIdentifier;
    var suffix = 2;
    while (identifiers.containsKey(identifier) &&
        identifiers[identifier] != key) {
      identifier = '$baseIdentifier$suffix';
      suffix++;
    }
    identifiers[identifier] = key;
    output.writeln('  static const $identifier = ${jsonEncode(key)};');
  }
  output.writeln('}');
  File(_keysOutputPath).writeAsStringSync(output.toString());
}

void _generateLoader(Map<String, Map<String, dynamic>> catalogs) {
  final sortedLocales = catalogs.keys.toList()..sort();
  for (final locale in sortedLocales) {
    _generateLocaleCatalog(locale, catalogs[locale]!);
  }

  final output = StringBuffer()
    ..writeln('// DO NOT EDIT. Generated by tool/generate_localizations.dart.')
    ..writeln()
    ..writeln("import 'dart:ui';")
    ..writeln()
    ..writeln(
      "import 'package:easy_localization/easy_localization.dart' show AssetLoader;",
    )
    ..writeln();

  for (final locale in sortedLocales) {
    output.writeln(
      "import 'codegen_loader_$locale.g.dart' as ${_localePrefix(locale)};",
    );
  }

  output
    ..writeln()
    ..writeln('class CodegenLoader extends AssetLoader {')
    ..writeln('  const CodegenLoader();')
    ..writeln()
    ..writeln('  @override')
    ..writeln(
      '  Future<Map<String, dynamic>?> load(String path, Locale locale) {',
    )
    ..writeln('    return Future.value(mapLocales[locale.toString()]);')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  static const Map<String, Map<String, dynamic>> mapLocales = {',
    );
  for (final locale in sortedLocales) {
    output.writeln("    '$locale': ${_localePrefix(locale)}.translations,");
  }
  output
    ..writeln('  };')
    ..writeln('}');
  File(_loaderOutputPath).writeAsStringSync(output.toString());
}

void _generateLocaleCatalog(String locale, Map<String, dynamic> translations) {
  final output = StringBuffer()
    ..writeln('// DO NOT EDIT. Generated by tool/generate_localizations.dart.')
    ..writeln()
    ..writeln('const Map<String, dynamic> translations =')
    ..writeln('    ${jsonEncode(translations)};');
  File(
    '$_sourceDirectory/codegen_loader_$locale.g.dart',
  ).writeAsStringSync(output.toString());
}

String _localePrefix(String locale) =>
    'locale_${locale.replaceAll(RegExp(r'[^A-Za-z0-9_]'), '_')}';

String _identifierFor(String key) {
  if (RegExp(r'^[a-z][A-Za-z0-9_]*$').hasMatch(key)) return key;
  final words = RegExp(
    r'[A-Za-z0-9]+',
  ).allMatches(key).map((match) => match.group(0)!).toList();
  if (words.isEmpty) return 'translationKey';

  var identifier = words.first.toLowerCase();
  for (final word in words.skip(1)) {
    identifier += '${word[0].toUpperCase()}${word.substring(1).toLowerCase()}';
  }
  if (RegExp(r'^\d').hasMatch(identifier)) {
    identifier = 'key${identifier[0].toUpperCase()}${identifier.substring(1)}';
  }
  return identifier;
}
