import 'dart:convert';
import 'dart:io';

const _sourcePath = 'assets/translations/en.json';
const _outputPath = 'lib/l10n/locale_keys.g.dart';

void main() {
  final translations = jsonDecode(File(_sourcePath).readAsStringSync());
  if (translations is! Map<String, dynamic>) {
    throw const FormatException('The English translation file must be a map.');
  }

  final identifiers = <String, String>{};
  final output = StringBuffer()
    ..writeln('// DO NOT EDIT. Generated by tool/generate_locale_keys.dart.')
    ..writeln()
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln()
    ..writeln('abstract final class LocaleKeys {');

  for (final key in translations.keys) {
    final baseIdentifier = _identifierFor(key);
    var identifier = baseIdentifier;
    var suffix = 2;
    while (identifiers.containsKey(identifier) &&
        identifiers[identifier] != key) {
      identifier = '$baseIdentifier$suffix';
      suffix++;
    }
    identifiers[identifier] = key;
    output.writeln('  static const $identifier = ${jsonEncode(key)};');
  }

  output.writeln('}');
  File(_outputPath).writeAsStringSync(output.toString());
  stdout.writeln('Generated ${translations.length} keys in $_outputPath');
}

String _identifierFor(String key) {
  if (RegExp(r'^[a-z][A-Za-z0-9_]*$').hasMatch(key)) return key;

  final words = RegExp(
    r'[A-Za-z0-9]+',
  ).allMatches(key).map((match) => match.group(0)!).toList();
  if (words.isEmpty) return 'translationKey';

  var identifier = words.first.toLowerCase();
  for (final word in words.skip(1)) {
    identifier += '${word[0].toUpperCase()}${word.substring(1).toLowerCase()}';
  }
  if (RegExp(r'^\d').hasMatch(identifier)) {
    identifier = 'key${identifier[0].toUpperCase()}${identifier.substring(1)}';
  }
  return identifier;
}
