[package]
name = "rust_lib_loanx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1"
flutter_rust_bridge = "=2.13.0"
prost = "0.14"
rand = "0.10"
s2n-quic = { version = "1.88", default-features = false, features = ["provider-address-token-default", "provider-tls-rustls"] }
tokio = { version = "1", features = ["io-util"] }

[build-dependencies]
prost-build = "0.14"
protoc-bin-vendored = "3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
