// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_and_hello_inner`, `read_frame`, `resolve_address`, `write_frame`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Negotiates the LoanX protocol through Rust so Flutter never owns QUIC or
/// Protobuf transport details. `trusted_certificate_pem` must authenticate
/// `server_name`; certificate validation is never disabled.
Future<ServerHello> connectAndHello({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String clientBuild,
}) => RustLib.instance.api.crateApiNetworkConnectAndHello(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  clientBuild: clientBuild,
);

class ServerHello {
  final bool success;
  final int protocolMajor;
  final String serverBuild;
  final int maximumFrameBytes;
  final List<String> capabilities;
  final String? errorMessage;

  const ServerHello({
    required this.success,
    required this.protocolMajor,
    required this.serverBuild,
    required this.maximumFrameBytes,
    required this.capabilities,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      protocolMajor.hashCode ^
      serverBuild.hashCode ^
      maximumFrameBytes.hashCode ^
      capabilities.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerHello &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          protocolMajor == other.protocolMajor &&
          serverBuild == other.serverBuild &&
          maximumFrameBytes == other.maximumFrameBytes &&
          capabilities == other.capabilities &&
          errorMessage == other.errorMessage;
}
