// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_and_hello_inner`, `read_frame`, `resolve_address`, `send_request`, `simple_network_result`, `write_frame`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<PendingLoanInvitation> createPendingLoan({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
  required String workspaceId,
  required String operationId,
  required String borrowerPhoneE164,
  required String borrowerName,
  required List<int> loanPayloadJson,
}) => RustLib.instance.api.crateApiNetworkCreatePendingLoan(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
  workspaceId: workspaceId,
  operationId: operationId,
  borrowerPhoneE164: borrowerPhoneE164,
  borrowerName: borrowerName,
  loanPayloadJson: loanPayloadJson,
);

Future<MyLenderProfile> myLenderProfile({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
}) => RustLib.instance.api.crateApiNetworkMyLenderProfile(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
);

Future<AccountBootstrap> accountBootstrap({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
}) => RustLib.instance.api.crateApiNetworkAccountBootstrap(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
);

Future<NetworkResult> publishPublicLender({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
  required String displayName,
  required String locality,
  required String city,
  required String postalCode,
  required String countryCode,
  required String minimumLoanMinor,
  required String maximumLoanMinor,
  required String currency,
  required int currencyScale,
  required List<String> categories,
  required bool available,
  required bool published,
  required String publicDescription,
}) => RustLib.instance.api.crateApiNetworkPublishPublicLender(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
  displayName: displayName,
  locality: locality,
  city: city,
  postalCode: postalCode,
  countryCode: countryCode,
  minimumLoanMinor: minimumLoanMinor,
  maximumLoanMinor: maximumLoanMinor,
  currency: currency,
  currencyScale: currencyScale,
  categories: categories,
  available: available,
  published: published,
  publicDescription: publicDescription,
);

Future<LenderSearchResult> searchPublicLenders({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
  required int area,
  required String query,
  required int limit,
  required String afterId,
}) => RustLib.instance.api.crateApiNetworkSearchPublicLenders(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
  area: area,
  query: query,
  limit: limit,
  afterId: afterId,
);

Future<NetworkResult> reportPublicLender({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
  required String profileId,
  required String reason,
}) => RustLib.instance.api.crateApiNetworkReportPublicLender(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
  profileId: profileId,
  reason: reason,
);

Future<NetworkResult> blockPublicLender({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
  required String profileId,
}) => RustLib.instance.api.crateApiNetworkBlockPublicLender(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
  profileId: profileId,
);

Future<ChatCredentials> requestChatCredentials({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
}) => RustLib.instance.api.crateApiNetworkRequestChatCredentials(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
);

Future<OtpChallenge> requestOtp({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String phoneE164,
}) => RustLib.instance.api.crateApiNetworkRequestOtp(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  phoneE164: phoneE164,
);

Future<AuthTokens> verifyOtp({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String challengeId,
  required String phoneE164,
  required String otp,
  required String preferredLanguage,
}) => RustLib.instance.api.crateApiNetworkVerifyOtp(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  challengeId: challengeId,
  phoneE164: phoneE164,
  otp: otp,
  preferredLanguage: preferredLanguage,
);

Future<NetworkResult> updateLanguage({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
  required String preferredLanguage,
}) => RustLib.instance.api.crateApiNetworkUpdateLanguage(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
  preferredLanguage: preferredLanguage,
);

Future<AuthTokens> refreshSession({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String refreshToken,
}) => RustLib.instance.api.crateApiNetworkRefreshSession(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  refreshToken: refreshToken,
);

/// Revokes the current server-side session. Local credentials should only be
/// removed after success, or explicitly as a user-selected offline logout.
Future<NetworkResult> logoutSession({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
}) => RustLib.instance.api.crateApiNetworkLogoutSession(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
);

/// Negotiates the LoanX protocol through Rust so Flutter never owns QUIC or
/// Protobuf transport details. `trusted_certificate_pem` must authenticate
/// `server_name`; certificate validation is never disabled.
Future<ServerHello> connectAndHello({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String clientBuild,
}) => RustLib.instance.api.crateApiNetworkConnectAndHello(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  clientBuild: clientBuild,
);

class AccountBootstrap {
  final bool success;
  final String userId;
  final String workspaceId;
  final String selfPartyId;
  final String phoneE164;
  final String preferredLanguage;
  final String? errorMessage;

  const AccountBootstrap({
    required this.success,
    required this.userId,
    required this.workspaceId,
    required this.selfPartyId,
    required this.phoneE164,
    required this.preferredLanguage,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      userId.hashCode ^
      workspaceId.hashCode ^
      selfPartyId.hashCode ^
      phoneE164.hashCode ^
      preferredLanguage.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountBootstrap &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          userId == other.userId &&
          workspaceId == other.workspaceId &&
          selfPartyId == other.selfPartyId &&
          phoneE164 == other.phoneE164 &&
          preferredLanguage == other.preferredLanguage &&
          errorMessage == other.errorMessage;
}

class AuthTokens {
  final bool success;
  final bool transportUnavailable;
  final String accessToken;
  final String refreshToken;
  final String userId;
  final String? errorMessage;

  const AuthTokens({
    required this.success,
    required this.transportUnavailable,
    required this.accessToken,
    required this.refreshToken,
    required this.userId,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      transportUnavailable.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      userId.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthTokens &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          transportUnavailable == other.transportUnavailable &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          userId == other.userId &&
          errorMessage == other.errorMessage;
}

class ChatCredentials {
  final bool success;
  final String jid;
  final String accessToken;
  final PlatformInt64 expiresAtMs;
  final String websocketUrl;
  final String? errorMessage;

  const ChatCredentials({
    required this.success,
    required this.jid,
    required this.accessToken,
    required this.expiresAtMs,
    required this.websocketUrl,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      jid.hashCode ^
      accessToken.hashCode ^
      expiresAtMs.hashCode ^
      websocketUrl.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatCredentials &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          jid == other.jid &&
          accessToken == other.accessToken &&
          expiresAtMs == other.expiresAtMs &&
          websocketUrl == other.websocketUrl &&
          errorMessage == other.errorMessage;
}

class LenderSearchResult {
  final bool success;
  final List<PublicLender> lenders;
  final String nextAfterId;
  final String? errorMessage;

  const LenderSearchResult({
    required this.success,
    required this.lenders,
    required this.nextAfterId,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      lenders.hashCode ^
      nextAfterId.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LenderSearchResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          lenders == other.lenders &&
          nextAfterId == other.nextAfterId &&
          errorMessage == other.errorMessage;
}

class MyLenderProfile {
  final bool success;
  final PublicLender? profile;
  final bool published;
  final String? errorMessage;

  const MyLenderProfile({
    required this.success,
    this.profile,
    required this.published,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      profile.hashCode ^
      published.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MyLenderProfile &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          profile == other.profile &&
          published == other.published &&
          errorMessage == other.errorMessage;
}

class NetworkResult {
  final bool success;
  final String? errorMessage;

  const NetworkResult({required this.success, this.errorMessage});

  @override
  int get hashCode => success.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage;
}

class OtpChallenge {
  final bool success;
  final String challengeId;
  final int expiresInSeconds;
  final String? errorMessage;

  const OtpChallenge({
    required this.success,
    required this.challengeId,
    required this.expiresInSeconds,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      challengeId.hashCode ^
      expiresInSeconds.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpChallenge &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          challengeId == other.challengeId &&
          expiresInSeconds == other.expiresInSeconds &&
          errorMessage == other.errorMessage;
}

class PendingLoanInvitation {
  final bool success;
  final String invitationId;
  final bool linkedToExistingAccount;
  final String? errorMessage;

  const PendingLoanInvitation({
    required this.success,
    required this.invitationId,
    required this.linkedToExistingAccount,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      invitationId.hashCode ^
      linkedToExistingAccount.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingLoanInvitation &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          invitationId == other.invitationId &&
          linkedToExistingAccount == other.linkedToExistingAccount &&
          errorMessage == other.errorMessage;
}

class PublicLender {
  final String id;
  final String displayName;
  final String locality;
  final String city;
  final String postalCode;
  final String countryCode;
  final PlatformInt64 minimumLoanMinor;
  final PlatformInt64 maximumLoanMinor;
  final String currency;
  final int currencyScale;
  final List<String> categories;
  final String verificationLevel;
  final bool available;
  final String publicDescription;

  const PublicLender({
    required this.id,
    required this.displayName,
    required this.locality,
    required this.city,
    required this.postalCode,
    required this.countryCode,
    required this.minimumLoanMinor,
    required this.maximumLoanMinor,
    required this.currency,
    required this.currencyScale,
    required this.categories,
    required this.verificationLevel,
    required this.available,
    required this.publicDescription,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      locality.hashCode ^
      city.hashCode ^
      postalCode.hashCode ^
      countryCode.hashCode ^
      minimumLoanMinor.hashCode ^
      maximumLoanMinor.hashCode ^
      currency.hashCode ^
      currencyScale.hashCode ^
      categories.hashCode ^
      verificationLevel.hashCode ^
      available.hashCode ^
      publicDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicLender &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          locality == other.locality &&
          city == other.city &&
          postalCode == other.postalCode &&
          countryCode == other.countryCode &&
          minimumLoanMinor == other.minimumLoanMinor &&
          maximumLoanMinor == other.maximumLoanMinor &&
          currency == other.currency &&
          currencyScale == other.currencyScale &&
          categories == other.categories &&
          verificationLevel == other.verificationLevel &&
          available == other.available &&
          publicDescription == other.publicDescription;
}

class ServerHello {
  final bool success;
  final int protocolMajor;
  final String serverBuild;
  final int maximumFrameBytes;
  final List<String> capabilities;
  final String? errorMessage;

  const ServerHello({
    required this.success,
    required this.protocolMajor,
    required this.serverBuild,
    required this.maximumFrameBytes,
    required this.capabilities,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      protocolMajor.hashCode ^
      serverBuild.hashCode ^
      maximumFrameBytes.hashCode ^
      capabilities.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerHello &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          protocolMajor == other.protocolMajor &&
          serverBuild == other.serverBuild &&
          maximumFrameBytes == other.maximumFrameBytes &&
          capabilities == other.capabilities &&
          errorMessage == other.errorMessage;
}
