// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_and_hello_inner`, `read_frame`, `resolve_address`, `send_request`, `write_frame`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ChatCredentials> requestChatCredentials({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
}) => RustLib.instance.api.crateApiNetworkRequestChatCredentials(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
);

Future<OtpChallenge> requestOtp({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String phoneE164,
}) => RustLib.instance.api.crateApiNetworkRequestOtp(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  phoneE164: phoneE164,
);

Future<AuthTokens> verifyOtp({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String challengeId,
  required String phoneE164,
  required String otp,
  required String preferredLanguage,
}) => RustLib.instance.api.crateApiNetworkVerifyOtp(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  challengeId: challengeId,
  phoneE164: phoneE164,
  otp: otp,
  preferredLanguage: preferredLanguage,
);

Future<NetworkResult> updateLanguage({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
  required String preferredLanguage,
}) => RustLib.instance.api.crateApiNetworkUpdateLanguage(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
  preferredLanguage: preferredLanguage,
);

Future<AuthTokens> refreshSession({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String refreshToken,
}) => RustLib.instance.api.crateApiNetworkRefreshSession(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  refreshToken: refreshToken,
);

/// Revokes the current server-side session. Local credentials should only be
/// removed after success, or explicitly as a user-selected offline logout.
Future<NetworkResult> logoutSession({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String accessToken,
}) => RustLib.instance.api.crateApiNetworkLogoutSession(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  accessToken: accessToken,
);

/// Negotiates the LoanX protocol through Rust so Flutter never owns QUIC or
/// Protobuf transport details. `trusted_certificate_pem` must authenticate
/// `server_name`; certificate validation is never disabled.
Future<ServerHello> connectAndHello({
  required String serverAddress,
  required String serverName,
  required String trustedCertificatePem,
  required String deviceId,
  required String clientBuild,
}) => RustLib.instance.api.crateApiNetworkConnectAndHello(
  serverAddress: serverAddress,
  serverName: serverName,
  trustedCertificatePem: trustedCertificatePem,
  deviceId: deviceId,
  clientBuild: clientBuild,
);

class AuthTokens {
  final bool success;
  final String accessToken;
  final String refreshToken;
  final String userId;
  final String? errorMessage;

  const AuthTokens({
    required this.success,
    required this.accessToken,
    required this.refreshToken,
    required this.userId,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      userId.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthTokens &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          userId == other.userId &&
          errorMessage == other.errorMessage;
}

class ChatCredentials {
  final bool success;
  final String jid;
  final String accessToken;
  final PlatformInt64 expiresAtMs;
  final String websocketUrl;
  final String? errorMessage;

  const ChatCredentials({
    required this.success,
    required this.jid,
    required this.accessToken,
    required this.expiresAtMs,
    required this.websocketUrl,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      jid.hashCode ^
      accessToken.hashCode ^
      expiresAtMs.hashCode ^
      websocketUrl.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatCredentials &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          jid == other.jid &&
          accessToken == other.accessToken &&
          expiresAtMs == other.expiresAtMs &&
          websocketUrl == other.websocketUrl &&
          errorMessage == other.errorMessage;
}

class NetworkResult {
  final bool success;
  final String? errorMessage;

  const NetworkResult({required this.success, this.errorMessage});

  @override
  int get hashCode => success.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage;
}

class OtpChallenge {
  final bool success;
  final String challengeId;
  final int expiresInSeconds;
  final String? errorMessage;

  const OtpChallenge({
    required this.success,
    required this.challengeId,
    required this.expiresInSeconds,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      challengeId.hashCode ^
      expiresInSeconds.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpChallenge &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          challengeId == other.challengeId &&
          expiresInSeconds == other.expiresInSeconds &&
          errorMessage == other.errorMessage;
}

class ServerHello {
  final bool success;
  final int protocolMajor;
  final String serverBuild;
  final int maximumFrameBytes;
  final List<String> capabilities;
  final String? errorMessage;

  const ServerHello({
    required this.success,
    required this.protocolMajor,
    required this.serverBuild,
    required this.maximumFrameBytes,
    required this.capabilities,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      protocolMajor.hashCode ^
      serverBuild.hashCode ^
      maximumFrameBytes.hashCode ^
      capabilities.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerHello &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          protocolMajor == other.protocolMajor &&
          serverBuild == other.serverBuild &&
          maximumFrameBytes == other.maximumFrameBytes &&
          capabilities == other.capabilities &&
          errorMessage == other.errorMessage;
}
