// DO NOT EDIT. Generated by tool/generate_localizations.dart.

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

import 'codegen_loader_as.g.dart' as locale_as;
import 'codegen_loader_bho.g.dart' as locale_bho;
import 'codegen_loader_bn.g.dart' as locale_bn;
import 'codegen_loader_br.g.dart' as locale_br;
import 'codegen_loader_en.g.dart' as locale_en;
import 'codegen_loader_gu.g.dart' as locale_gu;
import 'codegen_loader_hi.g.dart' as locale_hi;
import 'codegen_loader_kn.g.dart' as locale_kn;
import 'codegen_loader_mai.g.dart' as locale_mai;
import 'codegen_loader_ml.g.dart' as locale_ml;
import 'codegen_loader_mni.g.dart' as locale_mni;
import 'codegen_loader_mr.g.dart' as locale_mr;
import 'codegen_loader_mwr.g.dart' as locale_mwr;
import 'codegen_loader_ne.g.dart' as locale_ne;
import 'codegen_loader_or.g.dart' as locale_or;
import 'codegen_loader_pa.g.dart' as locale_pa;
import 'codegen_loader_ta.g.dart' as locale_ta;
import 'codegen_loader_te.g.dart' as locale_te;
import 'codegen_loader_ur.g.dart' as locale_ur;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, Map<String, dynamic>> mapLocales = {
    'as': locale_as.translations,
    'bho': locale_bho.translations,
    'bn': locale_bn.translations,
    'br': locale_br.translations,
    'en': locale_en.translations,
    'gu': locale_gu.translations,
    'hi': locale_hi.translations,
    'kn': locale_kn.translations,
    'mai': locale_mai.translations,
    'ml': locale_ml.translations,
    'mni': locale_mni.translations,
    'mr': locale_mr.translations,
    'mwr': locale_mwr.translations,
    'ne': locale_ne.translations,
    'or': locale_or.translations,
    'pa': locale_pa.translations,
    'ta': locale_ta.translations,
    'te': locale_te.translations,
    'ur': locale_ur.translations,
  };
}
