// DO NOT EDIT. Generated by tool/generate_localizations.dart.

// ignore_for_file: constant_identifier_names

abstract final class LocaleKeys {
  static const loanDetailsFor = "loanDetailsFor";
  static const daysCount = "daysCount";
  static const days = "days";
  static const until = "until";
  static const ifRedeemedBeforeThisDate = "ifRedeemedBeforeThisDate";
  static const notRecorded = "notRecorded";
  static const status = "status";
  static const addedByYou = "addedByYou";
  static const addedBySystem = "addedBySystem";
  static const systemHusband = "systemHusband";
  static const systemFather = "systemFather";
  static const systemWife = "systemWife";
  static const systemRing = "systemRing";
  static const systemAnklet = "systemAnklet";
  static const systemBracelet = "systemBracelet";
  static const systemArmlet = "systemArmlet";
  static const systemChain = "systemChain";
  static const systemEarRing = "systemEarRing";
  static const systemHeadLocket = "systemHeadLocket";
  static const systemMedal = "systemMedal";
  static const systemNecklace = "systemNecklace";
  static const systemLocket = "systemLocket";
  static const systemNeckBand = "systemNeckBand";
  static const systemGram = "systemGram";
  static const systemKilogram = "systemKilogram";
  static const systemMilligram = "systemMilligram";
  static const systemTola = "systemTola";
  static const shareAppSubject = "shareAppSubject";
  static const shareAppMessage = "shareAppMessage";
  static const loan = "loan";
  static const loans = "loans";
  static const loanx = "loanx";
  static const manage = "manage";
  static const appLanguage = "App language";
  static const chooseAppLanguage = "Choose app language";
  static const youCanChangeThisLaterFromAppPreferences =
      "You can change this later from App preferences.";
  static const searchLanguage = "searchLanguage";
  static const simpleInterest = "simpleInterest";
  static const compoundInterest = "compoundInterest";
  static const addLoan = "addLoan";
  static const addMortgage = "addMortgage";
  static const addMortgageMaterial = "addMortgageMaterial";
  static const addFamilyRelation = "addFamilyRelation";
  static const editLoan = "editLoan";
  static const editMortgage = "editMortgage";
  static const editMortgageMaterial = "editMortgageMaterial";
  static const editFamilyRelation = "editFamilyRelation";
  static const deleteLoan = "deleteLoan";
  static const deleteMortgage = "deleteMortgage";
  static const deleteMortgageMaterial = "deleteMortgageMaterial";
  static const deleteFamilyRelation = "deleteFamilyRelation";
  static const deleteMultipleLoan = "deleteMultipleLoan";
  static const deleteMultipleMortgage = "deleteMultipleMortgage";
  static const deleteMultipleMortgageMaterial =
      "deleteMultipleMortgageMaterial";
  static const deleteMultipleFamilyRelation = "deleteMultipleFamilyRelation";
  static const confirmDelete = "confirmDelete";
  static const confirmDeleteMultiple = "confirmDeleteMultiple";
  static const confirmDeleteMortgage = "confirmDeleteMortgage";
  static const confirmDeleteMultipleMortgage = "confirmDeleteMultipleMortgage";
  static const confirmDeleteMortgageMaterial = "confirmDeleteMortgageMaterial";
  static const confirmDeleteMultipleMortgageMaterial =
      "confirmDeleteMultipleMortgageMaterial";
  static const confirmDeleteFamilyRelation = "confirmDeleteFamilyRelation";
  static const confirmDeleteMultipleFamilyRelation =
      "confirmDeleteMultipleFamilyRelation";
  static const key15Days = "15 days";
  static const key7Days = "7 days";
  static const aFixedChargeAppliesIfTheItemIsRedeemedEarly =
      "A fixed charge applies if the item is redeemed early.";
  static const lockInDescription = "lockInDescription";
  static const noLockInHelper = "noLockInHelper";
  static const enterValidNumberOfDays = "enterValidNumberOfDays";
  static const about = "About";
  static const aboutLoanx = "About LoanX";
  static const active = "Active";
  static const activeLoans = "Active loans";
  static const amountDue = "Amount due";
  static const add = "Add";
  static const addRelation = "Add Relation";
  static const addAtLeastOnePledgedMaterialInManageBeforeCreatingALoan =
      "Add at least one pledged material in Manage before creating a loan.";
  static const addMaterial = "Add material";
  static const addRelationsLikeFatherMotherOrSiblingToGetStarted =
      "Add relations like Father, Mother, or Sibling to get started.";
  static const addUnit = "Add unit";
  static const additionalDetails = "Additional details";
  static const address = "Address";
  static const addressCanTBeEmpty = "Address can't be empty";
  static const allLoans = "All loans";
  static const amountReceived = "Amount received";
  static const anErrorOccurred = "An error occurred";
  static const appColor = "App color";
  static const appPreferences = "App preferences";
  static const moreActions = "More actions";
  static const areYouSureWantYouHaveReturnedThisMortgageToTheBorrowerAndClearTheLoan =
      "Are you sure want you have returned this mortgage to the borrower and clear the loan?";
  static const authenticationFailed = "Authentication failed";
  static const backUpNow = "Back up now";
  static const backupGoogleDrive = "Backup & Google Drive";
  static const borrower = "Borrower";
  static const borrowerAddress = "Borrower address";
  static const borrowerInformation = "Borrower information";
  static const borrowerMobileNumber = "Borrower mobile number";
  static const borrowerName = "Borrower name";
  static const borrowerNameCanTBeEmpty = "Borrower name can't be empty";
  static const borrowerReferenceOrMaterial = "Borrower, reference, or material";
  static const collectableAmount = "COLLECTABLE AMOUNT";
  static const call = "Call";
  static const cancel = "Cancel";
  static const changeBackupTime = "Change Backup Time";
  static const changeInterestRate = "Change Interest Rate";
  static const checkForUpdates = "Check for updates";
  static const close = "Close";
  static const closeLoanx = "Close LoanX";
  static const closeApp = "Close app";
  static const completeAndReturnItem = "Complete and return item";
  static const completeLoan = "Complete loan";
  static const completed = "Completed";
  static const compound = "Compound";
  static const calculatedInterest = "Calculated interest";
  static const confirmation = "Confirmation";
  static const contactSupport = "Contact support";
  static const couldNotOpenThePhoneApp = "Could not open the phone app";
  static const createALoan = "Create a loan";
  static const created = "Created";
  static const creatingYourSecureGoogleDriveBackup =
      "Creating your secure Google Drive backup…";
  static const dateOfLoan = "Date Of Loan";
  static const dateRangeOfLoan = "Date Range Of Loan";
  static const defaultLockIn = "Default lock-in";
  static const defaultLockInUpdated = "Default lock-in updated";
  static const defaultTermsAndConditions = "Default terms and conditions";
  static const defaultTermsAndConditionsUpdated =
      "Default terms and conditions updated";
  static const delete = "Delete";
  static const deleteMortgageMaterial2 = "Delete Mortgage Material";
  static const deletePermanently = "Delete permanently";
  static const deleteWeightUnit = "Delete weight unit?";
  static const depositorName = "Depositor Name";
  static const disconnectGoogleAccount = "Disconnect Google account";
  static const estimatedReceivable = "ESTIMATED RECEIVABLE";
  static const earlyRedemptionCharge = "Early redemption charge";
  static const edit = "Edit";
  static const editLoan2 = "Edit loan";
  static const enterAChargeGreaterThanZero = "Enter a charge greater than zero";
  static const enterAValidWeight = "Enter a valid weight";
  static const enterRepaymentCustodyOrOtherConditions =
      "Enter repayment, custody, or other conditions";
  static const enterTheFamilyRelation = "Enter the Family Relation";
  static const enterTheMortgageMaterial = "Enter the Mortgage Material";
  static const enterTheDefaultTermsForNewLoans =
      "Enter the default terms for new loans";
  static const exampleOunce = "Example: Ounce";
  static const exampleOz = "Example: oz";
  static const familyRelation = "Family Relation";
  static const familyRelationDeletedSuccessfully =
      "Family Relation Deleted Successfully";
  static const familyRelationCannotBeEmpty = "Family Relation cannot be empty";
  static const familyRelations = "Family Relations";
  static const filterLoans = "Filter loans";
  static const fixedAmount = "Fixed amount";
  static const frequency = "Frequency";
  static const goBack = "Go back";
  static const gotIt = "Got it";
  static const halfYearly = "Half-Yearly";
  static const helpFeedback = "Help & feedback";
  static const home = "Home";
  static const ifYouHaveUsedLoanxBeforeBringYourSavedRecordsBackFromGoogleDriveOtherwiseStartWithANewWorkspace =
      "If you have used LoanX before, bring your saved records back from Google Drive. Otherwise, start with a new workspace.";
  static const interest = "Interest";
  static const interestFrequency = "Interest Frequency";
  static const interestAndMortgageSettings = "Interest and mortgage settings";
  static const interestFrequency2 = "Interest frequency";
  static const interestRate = "Interest rate";
  static const interestType = "Interest type";
  static const itemConditionWitnessesOrOtherDetails =
      "Item condition, witnesses, or other details";
  static const itemReceivedBy = "Item received by";
  static const keyboardAwareListview = "Keyboard Aware ListView";
  static const learnAboutTheApp = "Learn about the app";
  static const learnWhatLoanxCanDo = "Learn what LoanX can do";
  static const loanDefaults = "Loan defaults";
  static const loanDetails = "Loan details";
  static const loanMarkedAsComplete = "Loan marked as complete";
  static const loanTerms = "Loan terms";
  static const loanx2 = "LoanX";
  static const loanxCouldNotFinishLoadingYourWorkspaceCloseTheAppAndTryAgain =
      "LoanX could not finish loading your workspace. Close the app and try again.";
  static const loans2 = "Loans";
  static const loansCouldNotBeLoaded = "Loans could not be loaded";
  static const lockInPeriod = "Lock-in period";
  static const manage2 = "Manage";
  static const materials = "Materials";
  static const materialsCouldNotBeLoaded = "Materials could not be loaded";
  static const message = "Message";
  static const monthly = "Monthly";
  static const mortgageMaterialType = "Mortgage Material Type";
  static const mortgageMaterialCannotBeEmpty =
      "Mortgage Material cannot be empty";
  static const mortgageMaterialDeletedSuccessfully =
      "Mortgage Material deleted successfully";
  static const mortgageMaterials = "Mortgage Materials";
  static const mortgageMaterial = "Mortgage material";
  static const mortgageTerm = "Mortgage term";
  static const mortgageWeight = "Mortgage weight";
  static const nameOfBorrowerOrAuthorisedRecipient =
      "Name of borrower or authorised recipient";
  static const newLoan = "New loan";
  static const noActivityHasBeenRecordedYet =
      "No activity has been recorded yet.";
  static const noDataFound = "No data found";
  static const noFamilyRelationsYet = "No family relations yet";
  static const noLockIn = "No lock-in";
  static const noMatchingLoans = "No matching loans";
  static const noMortgageMaterialsYet = "No mortgage materials yet";
  static const noWeightUnitsYet = "No weight units yet";
  static const notes = "Notes";
  static const notesOptional = "Notes (optional)";
  static const ok = "OK";
  static const ok2 = "Ok";
  static const phone = "Phone";
  static const pickAColor = "Pick a color!";
  static const pleaseRestartTheAppAndTryAgain =
      "Please restart the app and try again.";
  static const pleaseSelectAnOption = "Please select an option";
  static const pleaseTryAgainInAMoment = "Please try again in a moment.";
  static const pledgedItem = "Pledged item";
  static const pledgedMaterial = "Pledged material";
  static const principal = "Principal";
  static const principalAmount = "Principal amount";
  static const principalAmountCanTBeEmpty = "Principal amount can't be empty";
  static const principalOutstanding = "Principal outstanding";
  static const printLoanReceipt = "Print loan receipt";
  static const printReceipt = "Print receipt";
  static const printUsingAUsbOrBluetoothPrinter =
      "Print using a USB or Bluetooth printer";
  static const privacyPolicy = "Privacy Policy";
  static const provideAValidNumber = "Provide a valid number";
  static const quarterly = "Quarterly";
  static const rateLoanx = "Rate LoanX";
  static const receiptOrReferenceNumberOptional =
      "Receipt or reference number (optional)";
  static const recordTheHandoverDetailsForACompleteSettlementHistory =
      "Record the handover details for a complete settlement history.";
  static const reference = "Reference";
  static const referenceName = "Reference name";
  static const referenceNameCanTBeEmpty = "Reference name can't be empty";
  static const referenceNumber = "Reference number";
  static const relations = "Relations";
  static const relativeName = "Relative Name";
  static const restoreFromGoogleDrive = "Restore from Google Drive";
  static const restoreLatestBackup = "Restore latest backup";
  static const restoreYourLoanRecords = "Restore your loan records";
  static const restoringReplacesTheRecordsCurrentlyOnThisDevice =
      "Restoring replaces the records currently on this device.";
  static const restoringYourBackup = "Restoring your backup…";
  static const sms = "SMS";
  static const save = "Save";
  static const saveBorrowerAsContact = "Save borrower as contact";
  static const saveContact = "Save contact";
  static const saveOrOpenTheReceiptAsAPdfFile =
      "Save or open the receipt as a PDF file";
  static const searchCountry = "Search Country";
  static const searchCountryByNameOrCode = "Search Country by name or code";
  static const searchFilters = "Search filters";
  static const searchLoans = "Search loans";
  static const securingYourData = "Securing your data…";
  static const securityAndAppearance = "Security and appearance";
  static const selectInterestType = "Select Interest Type";
  static const selectPledgedMaterial = "Select pledged material";
  static const sentVia = "Sent via :";
  static const setColorUsingImage = "Set Color Using Image";
  static const setUpYourLoanMaterials = "Set up your loan materials";
  static const settlementNotes = "Settlement notes";
  static const settlementNotesOptional = "Settlement notes (optional)";
  static const shareApp = "Share App";
  static const sharePdf = "Share PDF";
  static const shareLoanDetails = "Share loan details";
  static const simple = "Simple";
  static const somethingWentWrong = "Something went wrong";
  static const startWithANewWorkspace = "Start with a new workspace";
  static const submit = "Submit";
  static const supportSharingAndUpdates = "Support, sharing, and updates";
  static const symbol = "Symbol";
  static const tapAddMaterialToCreateYourFirstOne =
      "Tap \"Add material\" to create your first one.";
  static const termsAndConditions = "Terms and conditions";
  static const termsAndConditionsOptional = "Terms and conditions (optional)";
  static const theseDefaultsApplyToNewLoansOnlyAndCanBeChangedOnEachLoan =
      "These defaults apply to new loans only and can be changed on each loan.";
  static const theseTermsAreCopiedIntoNewLoansAndCanBeEditedOnEachLoan =
      "These terms are copied into new loans and can be edited on each loan.";
  static const thisAccountStoresYourLoanxBackupsInGoogleDrive =
      "This account stores your LoanX backups in Google Drive.";
  static const tryAgain = "Try again";
  static const unableToCreateTheReceiptPleaseTryAgain =
      "Unable to create the receipt. Please try again.";
  static const unableToLoadLoanDetails = "Unable to load loan details";
  static const unableToLoadUnits = "Unable to load units";
  static const unit = "Unit";
  static const unitAlreadyExists = "Unit already exists";
  static const unitName = "Unit name";
  static const units = "Units";
  static const versionUnavailable = "Version unavailable";
  static const version = "Version…";
  static const viewConnectedAccount = "View connected account";
  static const weCouldNotVerifyYourIdentityUnlockYourDeviceAndTryAgain =
      "We could not verify your identity. Unlock your device and try again.";
  static const weight = "Weight";
  static const weightUnits = "Weight Units";
  static const welcomeToLoanx = "Welcome to LoanX";
  static const whatIsLoanx = "What is LoanX?";
  static const whatsapp = "WhatsApp";
  static const whatsapp2 = "Whatsapp";
  static const yearly = "Yearly";
  static const youCanManageBackupsLaterFromSettings =
      "You can manage backups later from Settings.";
  static const yourLendingWorkspace = "Your lending workspace";
  static const addNamedItem = "addNamedItem";
  static const dMmmYyyyHMmA = "d MMM yyyy, h:mm a";
  static const item = "item";
  static const itemNumber = "itemNumber";
  static const loanxDetails = "loanx Details";
  static const number = "number";
  static const typeSomethingIn = "typeSomethingIn";
  static const yearsCount = "yearsCount";
  static const loanValuePerUnit = "loanValuePerUnit";
  static const interestFrequencySet = "interestFrequencySet";
  static const backupTimeUpdated = "backupTimeUpdated";
  static const versionNumber = "versionNumber";
  static const deleteWeightUnitMessage = "deleteWeightUnitMessage";
  static const deleteNamedRelation = "deleteNamedRelation";
  static const noFilteredLoans = "noFilteredLoans";
  static const unableToSaveLoan = "unableToSaveLoan";
  static const deleteLoanCount = "deleteLoanCount";
  static const weightUnitType = "weightUnitType";
  static const aRevolutionaryAppToKeepRecordsOfLoansProvidedByTheUnorganizedSectorOfTheLendersAcrossTheWorldWithoutAnyPaperwork =
      "A revolutionary app to keep records of loans provided by the unorganized sector of the Lenders across the world without any paperwork.";
  static const activityHistory = "Activity history";
  static const addFamilyRelation2 = "Add Family Relation";
  static const addLoanRecord = "Add Loan Record";
  static const addMortgageMaterial2 = "Add Mortgage Material";
  static const addWeightUnit = "Add Weight Unit";
  static const addPledgedMaterial = "Add pledged material";
  static const appColorChanged = "App Color Changed";
  static const appGetsSecuredNowYouNeedToRestartTheApp =
      "App gets secured, Now you need to restart the app";
  static const appGetsUnsecuredNowYouNeedToRestartTheApp =
      "App gets unsecured, Now you need to restart the app";
  static const areYouSureYouWantToDeleteThisMortgageMaterialThisActionCannotBeUndone =
      "Are you sure you want to delete this mortgage material? This action cannot be undone.";
  static const backupCreatedSuccessfully = "Backup created successfully.";
  static const backupRestoredSuccessfully = "Backup restored successfully.";
  static const changeMortgageHoldingPeriod = "Change Mortgage Holding Period";
  static const confirmCreate = "Confirm & create";
  static const confirmSave = "Confirm & save";
  static const connectToTheInternetToRestoreABackup =
      "Connect to the internet to restore a backup.";
  static const couldNotCheckYourConnectionPleaseTryAgain =
      "Could not check your connection. Please try again.";
  static const couldNotOpenTheContactEditor =
      "Could not open the contact editor";
  static const couldNotRestoreYourBackupPleaseTryAgain =
      "Could not restore your backup. Please try again.";
  static const createLoan = "Create loan";
  static const createYourFirstLoanToTrackBorrowersPledgedMaterialsAndRepaymentStatus =
      "Create your first loan to track borrowers, pledged materials, and repayment status.";
  static const currentlyLoanxIsAvailableOnOnlyAndroidButSoonWillBeAccessibleToOtherPlatformsTooForMakingItAccessibleToAWideRangeOfUsers =
      "Currently, Loanx is available on only Android, But soon will be accessible to other platforms too for making it accessible to a wide range of users.";
  static const customMaterial = "Custom material";
  static const customRelation = "Custom relation";
  static const customUnit = "Custom unit";
  static const defaultHoldingPeriodIs5Years =
      "Default holding Period is 5 years";
  static const deleteThisLoan = "Delete this loan?";
  static const editFamilyRelation2 = "Edit Family Relation";
  static const editLoanRecord = "Edit Loan Record";
  static const editMortgageMaterial2 = "Edit Mortgage Material";
  static const editWeightUnit = "Edit Weight Unit";
  static const enterAPrincipalAmountGreaterThanZero =
      "Enter a principal amount greater than zero";
  static const enterTheFamilyRelation2 = "Enter the family relation";
  static const enterTheMaterialName = "Enter the material name";
  static const enterTheRecipientAndAValidAmountReceived =
      "Enter the recipient and a valid amount received";
  static const familyRelationAddedSuccessfully =
      "Family Relation added successfully";
  static const familyRelationAlreadyExists = "Family Relation already exists";
  static const googleAccountDisconnected = "Google account disconnected.";
  static const interestRateChanged = "Interest Rate Changed";
  static const interestTypeChangedSuccessfully =
      "Interest Type changed successfully";
  static const loanAlreadyCompleted = "Loan already completed";
  static const loanCreatedSuccessfully = "Loan created successfully";
  static const loanInformation = "Loan information";
  static const loanUpdatedSuccessfully = "Loan updated successfully";
  static const loanxIsASimpleAndEasyToUseAppThatAllowsYouToTrackYourLoansItIsDesignedToBeUserFriendlyAndIntuitiveMakingItEasyForAnyoneToManageTheirLoanRecords =
      "LoanX is a simple and easy to use app that allows you to track your loans. It is designed to be user-friendly and intuitive, making it easy for anyone to manage their loan records.";
  static const markAsComplete = "Mark as complete";
  static const mortgageHoldingPeriodChanged = "Mortgage Holding Period changed";
  static const mortgageMaterialAddedSuccessfully =
      "Mortgage Material added successfully";
  static const mortgageMaterialAlreadyExists =
      "Mortgage Material already exists";
  static const noAdditionalDetails = "No additional details";
  static const noLoansYet = "No loans yet";
  static const noNotesRecorded = "No notes recorded";
  static const notRecordedForThisOlderLoan = "Not recorded for this older loan";
  static const nowYouCanGiveMortgageToTheBorrower =
      "Now, you can give mortgage to the borrower";
  static const reviewTheUpdatedDetailsWithTheBorrowerSaveTheChangesOnlyAfterBothOfYouAgree =
      "Review the updated details with the borrower. Save the changes only after both of you agree.";
  static const reviewTheseDetailsWithTheBorrowerCreateTheRecordOnlyAfterBothOfYouAgree =
      "Review these details with the borrower. Create the record only after both of you agree.";
  static const saveChanges = "Save changes";
  static const saving = "Saving…";
  static const selectAFamilyRelationAndPledgedMaterial =
      "Select a family relation and pledged material";
  static const settlementRecord = "Settlement record";
  static const somethingWentWrongPleaseTryAgain =
      "Something went wrong. Please try again.";
  static const systemMaterial = "System material";
  static const systemRelation = "System relation";
  static const systemUnit = "System unit";
  static const theAppAlsoProvidesAFeatureToBackupYourDataEnsuringThatYourInformationIsSecureAndAccessibleInCaseOfAnyDataLoss =
      "The app also provides a feature to backup your data, ensuring that your information is secure and accessible in case of any data loss.";
  static const thisFamilyRelationWillBeRemovedPermanentlyThisActionCannotBeUndone =
      "This family relation will be removed permanently. This action cannot be undone.";
  static const thisFieldIsRequired = "This field is required";
  static const thisPermanentlyRemovesTheLoanRecordThisActionCannotBeUndone =
      "This permanently removes the loan record. This action cannot be undone.";
  static const thisPermanentlyRemovesTheSelectedLoanRecordsThisActionCannotBeUndone =
      "This permanently removes the selected loan records. This action cannot be undone.";
  static const traditionallyPracticedNowTechnologicallyAdvanced =
      "Traditionally practiced, now technologically advanced.";
  static const tryADifferentFilterToViewYourLoanRecords =
      "Try a different filter to view your loan records.";
  static const verifyLoanDetails = "Verify loan details";
  static const verifyUpdatedLoanDetails = "Verify updated loan details";
  static const whetherYouReASeasonedLoanProfessionalOrJustStartingOutLoanxIsThePerfectAppToHelpYouManageYourLoansSmoothlyEfficientlyAndEconomically =
      "Whether you're a seasoned loan professional or just starting out, Loanx is the perfect app to help you manage your loans smoothly, efficiently and economically.";
  static const withLoanxYouCanEasilyCreateUpdateAndDeleteLoanRecordsAsWellAsViewYourLoanHistory =
      "With LoanX, you can easily create, update, and delete loan records, as well as view your loan history.";
  static const youHaveNotSelectedAnyAccount =
      "You have not selected any account.";
  static const defaultYears = "defaultYears";
  static const mortgageHoldingPeriod = "mortgageHoldingPeriod";
  static const defaultInterestType = "defaultInterestType";
  static const defaultInterestFrequency = "defaultInterestFrequency";
  static const defaultInterestRate = "defaultInterestRate";
  static const currentInterestRate = "currentInterestRate";
  static const defaultTime = "defaultTime";
  static const defaultLockInSummary = "defaultLockInSummary";
  static const disableAppLock = "Disable app lock";
  static const enableAppLock = "Enable app lock";
  static const disableTheAppLockOnThisDevice =
      "Disable the app lock on this device?";
  static const enableAnAppLockOnThisDevice =
      "Enable an app lock on this device?";
  static const holdingPeriodCanTBe0 = "Holding Period can't be 0";
  static const notConnected = "Not connected";
  static const addAccount = "Add Account";
  static const changeAccount = "Change Account";
  static const googleAccount = "Google account";
  static const noDefaultTermsSet = "No default terms set";
  static const prefilledForNewLoans = "Prefilled for new loans";
  static const newLoansHaveNoLockInByDefault =
      "New loans have no lock-in by default";
  static const showUpiPaymentQr = "showUpiPaymentQr";
  static const createUpiPaymentQr = "createUpiPaymentQr";
  static const receivingUpiId = "receivingUpiId";
  static const upiIdHint = "upiIdHint";
  static const enterValidUpiId = "enterValidUpiId";
  static const invalidUpiHandle = "invalidUpiHandle";
  static const defaultUpiId = "defaultUpiId";
  static const noDefaultUpiIdSet = "noDefaultUpiIdSet";
  static const defaultUpiIdHelper = "defaultUpiIdHelper";
  static const defaultUpiIdUpdated = "defaultUpiIdUpdated";
  static const amount = "amount";
  static const enterAmountGreaterThanZero = "enterAmountGreaterThanZero";
  static const createQr = "createQr";
  static const loanRepaymentFor = "loanRepaymentFor";
  static const scanToPayWithUpi = "scanToPayWithUpi";
  static const verifyUpiRecipient = "verifyUpiRecipient";
  static const done = "done";
  static const noLoanxBackupIsAvailableInGoogleDrive =
      "No LoanX backup is available in Google Drive.";
  static const restartTheAppToApplyTheUpdate =
      "Restart the app to apply the update.";
  static const noUpdatesAvailable = "No updates available";
  static const googleAccountConnected = "Google account connected.";
  static const googleAccountUpdated = "Google account updated.";
  static const phoneLoginPrompt = "phoneLoginPrompt";
  static const phoneNumber = "phoneNumber";
  static const continueAction = "continueAction";
  static const validMobileNumberHelper = "validMobileNumberHelper";
  static const verifyYourNumber = "verifyYourNumber";
  static const enterAValidBorrowerPhoneNumber =
      "Enter a valid borrower phone number";
  static const otpSentTo = "otpSentTo";
  static const sixDigitVerificationCode = "sixDigitVerificationCode";
  static const verifyAndContinue = "verifyAndContinue";
  static const resendCode = "resendCode";
  static const resendCodeIn = "resendCodeIn";
  static const changePhoneNumber = "changePhoneNumber";
  static const phoneVerificationUnavailable = "phoneVerificationUnavailable";
  static const couldNotSendCode = "couldNotSendCode";
  static const invalidVerificationCode = "invalidVerificationCode";
  static const couldNotVerifyCode = "couldNotVerifyCode";
  static const chooseAccountType = "chooseAccountType";
  static const accountTypePrompt = "accountTypePrompt";
  static const lenderAccount = "lenderAccount";
  static const lenderAccountDescription = "lenderAccountDescription";
  static const borrowerAccount = "borrowerAccount";
  static const borrowerAccountDescription = "borrowerAccountDescription";
  static const bothLendingAndBorrowing = "bothLendingAndBorrowing";
  static const bothAccountDescription = "bothAccountDescription";
  static const preferenceCanChangeLater = "preferenceCanChangeLater";
  static const findLenders = "Find lenders";
  static const findLendersNearYou = "Find lenders near you";
  static const discoverLendersNearYou = "Discover lenders near you";
  static const searchPublicLenderProfilesByAnAreaYouChooseYourPreciseLocationIsNeverShared =
      "Search public lender profiles by an area you choose. Your precise location is never shared.";
  static const searchWithin = "Search within";
  static const locality = "Locality";
  static const city = "City";
  static const pincode = "Pincode";
  static const localityOrNeighbourhood = "Locality or neighbourhood";
  static const pincodeOrPostalCode = "Pincode or postal code";
  static const forExampleIndiranagar = "For example, Indiranagar";
  static const forExampleBengaluru = "For example, Bengaluru";
  static const forExample560038 = "For example, 560038";
  static const enterAnAreaToSearch = "Enter an area to search";
  static const enterAValidPincodeOrPostalCode =
      "Enter a valid pincode or postal code";
  static const enterAtLeast2Characters = "Enter at least 2 characters";
  static const searchLenders = "Search lenders";
  static const searching = "Searching…";
  static const clear = "Clear";
  static const chooseWhereToSearch = "Choose where to search";
  static const selectALocalityCityOrPincodeToFindPublicLenderProfiles =
      "Select a locality, city, or pincode to find public lender profiles.";
  static const searchUnavailable = "Search unavailable";
  static const lendersCouldNotBeLoadedPleaseTryAgain =
      "Lenders could not be loaded. Please try again.";
  static const noLendersFound = "No lenders found";
  static const noPublicLenderProfilesAreAvailableInThisAreaYetTryANearbyCityOrLocality =
      "No public lender profiles are available in this area yet. Try a nearby city or locality.";
  static const loanRange = "Loan range";
  static const viewProfile = "View profile";
  static const verificationAppliesOnlyToTheStatedAttributeAndIsNotASafetyGuarantee =
      "Verification applies only to the stated attribute and is not a safety guarantee.";
  static const lenderProfile = "Lender profile";
  static const phoneVerified = "Phone verified";
  static const identityVerified = "Identity verified";
  static const businessVerified = "Business verified";
  static const loanxHelpsYouDiscoverLendersItDoesNotGuaranteeALenderOrApproveDisburseOrCollectALoan =
      "LoanX helps you discover lenders. It does not guarantee a lender or approve, disburse, or collect a loan.";
  static const myLoans = "My loans";
  static const myLenders = "My lenders";
  static const myBorrowers = "My borrowers";
  static const connectAccount = "Connect account";
  static const signInAsBorrower = "Sign in as borrower";
  static const couldNotSendVerificationCode =
      "Could not send verification code";
  static const verificationUnavailable = "Verification unavailable";
  static const pleaseEnterTheVerificationCode =
      "Please enter the verification code";
  static const invalidVerificationCode2 = "Invalid verification code";
  static const accountCouldNotBeLinkedToThisWorkspace =
      "Account could not be linked to this workspace";
  static const repaymentHistory = "Repayment history";
  static const recordRepayment = "Record repayment";
  static const recordedRepayments = "Recorded repayments";
  static const legacyInterestRemainsOnTheExistingLoanRecordUntilItIsMigratedToVersionedTerms =
      "Legacy interest remains on the existing loan record until it is migrated to versioned terms.";
  static const noRepaymentsRecorded = "No repayments recorded";
  static const repaymentHistoryCouldNotBeLoaded =
      "Repayment history could not be loaded";
  static const repaymentCouldNotBeRecorded = "Repayment could not be recorded";
  static const repaymentCouldNotBeReversed = "Repayment could not be reversed";
  static const reverseRepayment = "Reverse repayment";
  static const repaymentReversed = "Repayment reversed";
  static const repayment = "Repayment";
  static const reverse = "Reverse";
  static const amount2 = "Amount";
  static const borrowersCouldNotBeLoaded = "Borrowers could not be loaded";
  static const noBorrowersYet = "No borrowers yet";
  static const noConnectedLenders = "No connected lenders";
  static const loanxLender = "LoanX lender";
  static const lenderNotifications = "Lender notifications";
  static const noLenderNotifications = "No lender notifications";
  static const loansFromLoanxLenders = "Loans from LoanX lenders";
  static const noConnectedLoans = "No connected loans";
  static const loansIssuedToYouByConnectedLoanxLendersWillAppearHere =
      "Loans issued to you by connected LoanX lenders will appear here.";
  static const borrowing = "Borrowing";
  static const reportProfile = "Report profile";
  static const blockLender = "Block lender";
  static const reason = "Reason";
  static const enterAtLeast10Characters = "Enter at least 10 characters";
  static const submitReport = "Submit report";
  static const reportSubmitted = "Report submitted";
  static const blockLender2 = "Block lender?";
  static const thisProfileWillNoLongerAppearInYourSearches =
      "This profile will no longer appear in your searches.";
  static const block = "Block";
  static const lenderBlocked = "Lender blocked";
  static const actionCouldNotBeCompleted = "Action could not be completed";
  static const publicLenderProfile = "Public lender profile";
  static const onlyTheDetailsYouEnterHereArePublishedYourPhoneAddressAndPrivateLoansStayPrivate =
      "Only the details you enter here are published. Your phone, address and private loans stay private.";
  static const publicProfileCouldNotBeLoadedConnectAndTryAgain =
      "Public profile could not be loaded. Connect and try again.";
  static const publicProfileSaved = "Public profile saved";
  static const publicProfileCouldNotBeSaved =
      "Public profile could not be saved";
  static const publicName = "Public name";
  static const enter2120Characters = "Enter 2–120 characters";
  static const currency = "Currency";
  static const minimumLoanAmount = "Minimum loan amount";
  static const maximumLoanAmount = "Maximum loan amount";
  static const loanCategoriesSeparatedByCommas =
      "Loan categories, separated by commas";
  static const publicDescription = "Public description";
  static const acceptingEnquiries = "Accepting enquiries";
  static const publishInLenderSearch = "Publish in lender search";
  static const youCanUnpublishThisProfileAtAnyTime =
      "You can unpublish this profile at any time.";
  static const enterAValidAmount = "Enter a valid amount";
  static const loadMoreLenders = "Load more lenders";
  static const loading = "Loading…";
  static const moreLendersCouldNotBeLoadedPleaseTryAgain =
      "More lenders could not be loaded. Please try again.";
  static const syncNow = "Sync now";
  static const syncing = "Syncing";
  static const couldNotSyncCheckYourConnectionAndTryAgain =
      "Could not sync. Check your connection and try again.";
  static const recordsSynced = "Records synced.";
  static const someRecordsCouldNotSyncAndWillBeRetried =
      "Some records could not sync and will be retried.";
}
