// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class HelloResponse {
  final int selectedProtocolMajor;
  final String serverBuild;
  final int maximumFrameBytes;
  final List<String> capabilities;

  const HelloResponse({
    required this.selectedProtocolMajor,
    required this.serverBuild,
    required this.maximumFrameBytes,
    required this.capabilities,
  });

  @override
  int get hashCode =>
      selectedProtocolMajor.hashCode ^
      serverBuild.hashCode ^
      maximumFrameBytes.hashCode ^
      capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HelloResponse &&
          runtimeType == other.runtimeType &&
          selectedProtocolMajor == other.selectedProtocolMajor &&
          serverBuild == other.serverBuild &&
          maximumFrameBytes == other.maximumFrameBytes &&
          capabilities == other.capabilities;
}

class PingResponse {
  final Uint8List opaque;
  final PlatformInt64 serverUnixTimeMs;

  const PingResponse({required this.opaque, required this.serverUnixTimeMs});

  @override
  int get hashCode => opaque.hashCode ^ serverUnixTimeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PingResponse &&
          runtimeType == other.runtimeType &&
          opaque == other.opaque &&
          serverUnixTimeMs == other.serverUnixTimeMs;
}

class ProtocolError {
  final int code;
  final String message;
  final bool retryable;

  const ProtocolError({
    required this.code,
    required this.message,
    required this.retryable,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          retryable == other.retryable;
}
